/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import cls.Supplier;
import cls.ViewSupplierStock;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author esh
 */
public class FrameViewSupplierStock extends javax.swing.JFrame {

    String LOACATION_ID = null;
    String USER_NAME = null;
    
    public static String id_Supplier = null;
    public static String supplierName = null;

    /**
     * Creates new form FrameCategory
     */
    public FrameViewSupplierStock() {
        initComponents();
    }

    public FrameViewSupplierStock(String LOCATIONID, String USERNAME) {
        initComponents();

        ViewSupplierStock s = new ViewSupplierStock();
        s.searchAll();

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldSupplierCode = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldCompanyName = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextFieldSupplierName = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Supplier View");
        setPreferredSize(new java.awt.Dimension(820, 480));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Supplier View");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Supplier Code");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jTextFieldSupplierCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldSupplierCodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSupplierCodeFocusLost(evt);
            }
        });
        jTextFieldSupplierCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSupplierCodeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSupplierCodeKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldSupplierCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 210, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Company Name");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jTextFieldCompanyName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldCompanyNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCompanyNameFocusLost(evt);
            }
        });
        jTextFieldCompanyName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCompanyNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCompanyNameKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 210, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search1.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search2.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 90, 74, 30));

        jScrollPane1.setAutoscrolls(true);

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO", "CODE", "NAME WITH INITIALS", "COMPANY NAME", "BRANCH", "PHONE NO 01"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(180);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(150);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 770, 290));

        jTextFieldSupplierName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldSupplierNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSupplierNameFocusLost(evt);
            }
        });
        jTextFieldSupplierName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSupplierNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSupplierNameKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldSupplierName, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 210, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("Supplier Name");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSupplierCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSupplierCodeFocusGained

    }//GEN-LAST:event_jTextFieldSupplierCodeFocusGained

    private void jTextFieldSupplierCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSupplierCodeFocusLost

    }//GEN-LAST:event_jTextFieldSupplierCodeFocusLost

    private void jTextFieldSupplierCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSupplierCodeKeyReleased

        String s = jTextFieldSupplierCode.getText();
        jTextFieldSupplierCode.setText(s.toUpperCase());

    }//GEN-LAST:event_jTextFieldSupplierCodeKeyReleased

    private void jTextFieldSupplierCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSupplierCodeKeyTyped

    }//GEN-LAST:event_jTextFieldSupplierCodeKeyTyped

    private void jTextFieldCompanyNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCompanyNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCompanyNameFocusGained

    private void jTextFieldCompanyNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCompanyNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCompanyNameFocusLost

    private void jTextFieldCompanyNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCompanyNameKeyReleased

        String s = jTextFieldCompanyName.getText();
        jTextFieldCompanyName.setText(s.toUpperCase());
    }//GEN-LAST:event_jTextFieldCompanyNameKeyReleased

    private void jTextFieldCompanyNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCompanyNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCompanyNameKeyTyped

    private void jTextFieldSupplierNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSupplierNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSupplierNameFocusGained

    private void jTextFieldSupplierNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSupplierNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSupplierNameFocusLost

    private void jTextFieldSupplierNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSupplierNameKeyReleased

        String s = jTextFieldSupplierName.getText();
        jTextFieldSupplierName.setText(s.toUpperCase());

    }//GEN-LAST:event_jTextFieldSupplierNameKeyReleased

    private void jTextFieldSupplierNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSupplierNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSupplierNameKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        ViewSupplierStock s = new ViewSupplierStock();
        s.search();
    }//GEN-LAST:event_jButton3ActionPerformed

    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        DefaultTableModel dtm = new DefaultTableModel();
        dtm = (DefaultTableModel) FrameViewSupplierStock.jTable1.getModel();

        int i = FrameViewSupplierStock.jTable1.getSelectedRow();
        int j = FrameViewSupplierStock.jTable1.getSelectedColumn();

        String s = dtm.getValueAt(i, j).toString();

        id_Supplier = dtm.getValueAt(i, 0).toString();
        supplierName = dtm.getValueAt(i, 2).toString();
        

    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameViewSupplierStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameViewSupplierStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameViewSupplierStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameViewSupplierStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameViewSupplierStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    public static javax.swing.JTextField jTextFieldCompanyName;
    public static javax.swing.JTextField jTextFieldSupplierCode;
    public static javax.swing.JTextField jTextFieldSupplierName;
    // End of variables declaration//GEN-END:variables
}
