/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import cls.Product;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author esh
 */
public class FrameViewProduct extends javax.swing.JFrame {

    String LOACATION_ID = null;
    String USER_NAME = null;

    /**
     * Creates new form FrameCategory
     */
    public FrameViewProduct() {
        initComponents();
    }

    public FrameViewProduct(String LOCATIONID, String USERNAME) {
        initComponents();

        LOACATION_ID = LOCATIONID;
        USER_NAME = USERNAME;

        Product p = new Product();
        p.searchAll();
        p.loadCategory2();
        p.loadSubCategory();
        p.loadSupplier();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldProductCode = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jComboBoxCategoryName = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        jComboBoxSubCategory = new javax.swing.JComboBox();
        jTextFieldProductName = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jComboBoxSupplier = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View Product");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Product Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Product Code");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jTextFieldProductCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldProductCodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldProductCodeFocusLost(evt);
            }
        });
        jTextFieldProductCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldProductCodeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldProductCodeKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldProductCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 210, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search1.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search2.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 140, 74, 30));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO", "CODE", "PRODUCT NAME", "CATEGORY", "SUB CATEGORY", "DESCRIPTION", "SUPPLIER", "COST PRICE", "SELLING PRICE", "OPENING STOCK", "DISCOUNT", "VAT", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(12).setPreferredWidth(40);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 1170, 370));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("Category Name");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, -1, -1));

        jComboBoxCategoryName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBoxCategoryNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxCategoryNameFocusLost(evt);
            }
        });
        jComboBoxCategoryName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoryNameActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxCategoryName, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 50, 207, 22));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("Sub Category Name");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jComboBoxSubCategory.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBoxSubCategoryFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxSubCategoryFocusLost(evt);
            }
        });
        jComboBoxSubCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSubCategoryActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxSubCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 207, 22));

        jTextFieldProductName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldProductNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldProductNameFocusLost(evt);
            }
        });
        jTextFieldProductName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldProductNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldProductNameKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 210, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("Product Name");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel32.setText("Supplier");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        jComboBoxSupplier.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBoxSupplierFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxSupplierFocusLost(evt);
            }
        });
        jComboBoxSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSupplierActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 620, 22));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 290, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1230, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldProductCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldProductCodeFocusGained

    }//GEN-LAST:event_jTextFieldProductCodeFocusGained

    private void jTextFieldProductCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldProductCodeFocusLost

    }//GEN-LAST:event_jTextFieldProductCodeFocusLost

    private void jTextFieldProductCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProductCodeKeyReleased

        String s = jTextFieldProductCode.getText();
        jTextFieldProductCode.setText(s.toUpperCase());
    }//GEN-LAST:event_jTextFieldProductCodeKeyReleased

    private void jTextFieldProductCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProductCodeKeyTyped

    }//GEN-LAST:event_jTextFieldProductCodeKeyTyped

    private void jComboBoxCategoryNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxCategoryNameFocusGained

    }//GEN-LAST:event_jComboBoxCategoryNameFocusGained

    private void jComboBoxCategoryNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxCategoryNameFocusLost

    }//GEN-LAST:event_jComboBoxCategoryNameFocusLost
    String id_category = null;
    private void jComboBoxCategoryNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoryNameActionPerformed

        try {

            ResultSet rs = cls.db.myConnection().createStatement().executeQuery("SELECT * FROM category WHERE category_name='" + jComboBoxCategoryName.getSelectedItem().toString() + "' ");
            while (rs.next()) {
                id_category = rs.getString("idcategory");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, e);
        }

    }//GEN-LAST:event_jComboBoxCategoryNameActionPerformed

    private void jComboBoxSubCategoryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxSubCategoryFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSubCategoryFocusGained

    private void jComboBoxSubCategoryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxSubCategoryFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSubCategoryFocusLost
    String id_subcategory = null;
    private void jComboBoxSubCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSubCategoryActionPerformed

        try {

            ResultSet rs = cls.db.myConnection().createStatement().executeQuery("SELECT * FROM sub_category WHERE sub_category_name='" + jComboBoxSubCategory.getSelectedItem().toString() + "' ");
            while (rs.next()) {
                id_subcategory = rs.getString("idsub_category");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jComboBoxSubCategoryActionPerformed

    private void jTextFieldProductNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldProductNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProductNameFocusGained

    private void jTextFieldProductNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldProductNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProductNameFocusLost

    private void jTextFieldProductNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProductNameKeyReleased

        String s = jTextFieldProductName.getText();
        jTextFieldProductName.setText(s.toUpperCase());
        
    }//GEN-LAST:event_jTextFieldProductNameKeyReleased

    private void jTextFieldProductNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProductNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProductNameKeyTyped

    private void jComboBoxSupplierFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxSupplierFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSupplierFocusGained

    private void jComboBoxSupplierFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxSupplierFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSupplierFocusLost
    String supplier_code = null;
    private void jComboBoxSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSupplierActionPerformed

        String s = jComboBoxSupplier.getSelectedItem().toString();
        supplier_code = s.substring(0, 4);
    }//GEN-LAST:event_jComboBoxSupplierActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        Product p = new Product();
        if (jTextFieldProductCode.getText().length() == 0 && jTextFieldProductName.getText().length() == 0
                && jComboBoxCategoryName.getSelectedIndex() == 0 && jComboBoxSubCategory.getSelectedIndex() == 0 && jComboBoxSupplier.getSelectedIndex() == 0) {

            p.searchAll();
            
            int i = FrameViewProduct.jTable1.getRowCount();
            jLabel2.setText("NO OF PRODUCT = " + i);

        } else {
            p.searchViewProduct(id_category, id_subcategory, supplier_code);

        }

    }//GEN-LAST:event_jButton3ActionPerformed
public static String product_code=null;
public static String product_name=null;
public static String selling_price=null;
public static String product_id=null;
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        DefaultTableModel dtm = new DefaultTableModel();
        dtm = (DefaultTableModel) FrameViewProduct.jTable1.getModel();

        int i = FrameViewProduct.jTable1.getSelectedRow();
        int j = FrameViewProduct.jTable1.getSelectedColumn();

        String s = dtm.getValueAt(i, j).toString();

        product_id = dtm.getValueAt(i, 0).toString();
        product_code = dtm.getValueAt(i, 1).toString();
        product_name = dtm.getValueAt(i, 2).toString();
        selling_price = dtm.getValueAt(i, 8).toString();
        
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameViewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameViewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameViewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameViewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameViewProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    public static javax.swing.JComboBox jComboBoxCategoryName;
    public static javax.swing.JComboBox jComboBoxSubCategory;
    public static javax.swing.JComboBox jComboBoxSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    public static javax.swing.JTextField jTextFieldProductCode;
    public static javax.swing.JTextField jTextFieldProductName;
    // End of variables declaration//GEN-END:variables
}
