/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import cls.AccessPoint;
import cls.Product;
import cls.Stock;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author esh
 */
public class FrameStockUpdate extends javax.swing.JFrame {

    String LOACATION_ID = null;
    String USER_NAME = null;
    
    

    public static String PRODUCT_ID = null;

    /**
     * Creates new form FrameCategory
     */
    public FrameStockUpdate() {
        initComponents();
    }

    public FrameStockUpdate(String LOCATIONID, String USERNAME) {
        initComponents();

        LOACATION_ID = LOCATIONID;
        USER_NAME = USERNAME;

        showTimer();
        
        loadProduct();
        loadSupplier();
        
        jButton1.setEnabled(false);
        
        AutoCompleteDecorator.decorate(jComboBoxProductCode);
        AutoCompleteDecorator.decorate(jComboBoxSupplier);
        
    }

    void showTimer() {
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                Date d = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                        jTextFieldDate.setText(sdf.format(d));
            }
        }).start();
    }
    
    void loadProduct() {

        try {

            ResultSet rs = cls.db.myConnection().createStatement().executeQuery("SELECT * FROM product ");

            Vector v = new Vector();
            v.add("--SELECT--");
            while (rs.next()) {

                v.add(rs.getString("p_code"));
            }

            jComboBoxProductCode.setModel(new DefaultComboBoxModel(v));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }

    }
    
    void loadSupplier() {

        try {

            ResultSet rs = cls.db.myConnection().createStatement().executeQuery("SELECT * FROM supplier WHERE status='" + "ACTIVE" + "' ");

            Vector v = new Vector();

            v.add("--SELECT--");
            while (rs.next()) {

                String idSupplier = rs.getString("idsupplier");
                String fullname = rs.getString("supplier_name");
                String setName = idSupplier + " - " + fullname;
                v.add(setName);

            }

            jComboBoxSupplier.setModel(new DefaultComboBoxModel(v));

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, e);
        }

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldStockId = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDiscription = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        jTextFieldProductName = new javax.swing.JTextField();
        jTextFieldPricePerUnit = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTextFieldQty = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextFieldTotalAmount = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLabelSupplierId = new javax.swing.JLabel();
        jLabelProductCode = new javax.swing.JLabel();
        jLabelProductName = new javax.swing.JLabel();
        jLabelPricePerUnit = new javax.swing.JLabel();
        jLabelQty = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextFieldRefNo = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabelRef = new javax.swing.JLabel();
        jComboBoxProductCode = new javax.swing.JComboBox();
        jLabelCost = new javax.swing.JLabel();
        jTextFieldCost = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jComboBoxSupplier = new javax.swing.JComboBox();
        jTextFieldDate = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableimei = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stock Update");
        setPreferredSize(new java.awt.Dimension(800, 660));
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Stock Update");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("---------------------------------------------------------------------Product Info------------------------------------------------------------------------");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 800, -1));

        jTextFieldStockId.setEditable(false);
        jTextFieldStockId.setText("01");
        jTextFieldStockId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldStockIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldStockIdFocusLost(evt);
            }
        });
        jTextFieldStockId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldStockIdKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldStockIdKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldStockId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 210, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Supplier ID*");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("Product Code*");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("Product Name*");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("Price Per Unit*");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jTextAreaDiscription.setColumns(20);
        jTextAreaDiscription.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDiscription);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 210, 80));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("Date*");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, -1));

        jTextFieldProductName.setEditable(false);
        jTextFieldProductName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldProductNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldProductNameFocusLost(evt);
            }
        });
        jTextFieldProductName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldProductNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldProductNameKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 210, -1));

        jTextFieldPricePerUnit.setEditable(false);
        jTextFieldPricePerUnit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPricePerUnitFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPricePerUnitFocusLost(evt);
            }
        });
        jTextFieldPricePerUnit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPricePerUnitKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPricePerUnitKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldPricePerUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 210, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel33.setText("Stock ID*");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("-----------------------------------------------------------------Stock & Supplier Details-----------------------------------------------------------------");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 800, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel35.setText("Qty*");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, -1));

        jTextFieldQty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldQtyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldQtyFocusLost(evt);
            }
        });
        jTextFieldQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQtyActionPerformed(evt);
            }
        });
        jTextFieldQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldQtyKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldQtyKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 210, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel36.setText("Total Amount");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        jTextFieldTotalAmount.setEditable(false);
        jTextFieldTotalAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldTotalAmountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTotalAmountFocusLost(evt);
            }
        });
        jTextFieldTotalAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldTotalAmountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTotalAmountKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldTotalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 210, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel37.setText("Description");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, -1, -1));

        jLabelDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDate.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 200, 15));

        jLabelSupplierId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSupplierId.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelSupplierId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 210, 15));

        jLabelProductCode.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelProductCode.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelProductCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 210, 15));

        jLabelProductName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelProductName.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 200, 15));

        jLabelPricePerUnit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPricePerUnit.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelPricePerUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 200, 15));

        jLabelQty.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelQty.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 200, 15));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update1.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 590, 74, 30));

        jTextFieldRefNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldRefNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldRefNoFocusLost(evt);
            }
        });
        jTextFieldRefNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldRefNoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldRefNoKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldRefNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 210, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel38.setText("Reference No *");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search1.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 74, 30));

        jLabelRef.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelRef.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 200, 15));

        jComboBoxProductCode.setEditable(true);
        jComboBoxProductCode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxProductCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProductCodeActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxProductCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 210, 21));

        jLabelCost.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCost.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 200, 15));

        jTextFieldCost.setEditable(false);
        jTextFieldCost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCostKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCostKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 210, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setText("Cost*");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jComboBoxSupplier.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBoxSupplierFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxSupplierFocusLost(evt);
            }
        });
        jComboBoxSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSupplierActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 210, 22));

        jTextFieldDate.setEditable(false);
        jTextFieldDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDateFocusLost(evt);
            }
        });
        jTextFieldDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldDateKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDateKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 210, -1));

        jTableimei.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTableimei.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PRODUCT", "IMEI 1", "IMEI 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableimei.setRowHeight(20);
        jTableimei.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableimeiMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableimei);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 750, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldStockIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldStockIdFocusGained

    }//GEN-LAST:event_jTextFieldStockIdFocusGained

    private void jTextFieldStockIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldStockIdFocusLost

    }//GEN-LAST:event_jTextFieldStockIdFocusLost

    private void jTextFieldStockIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldStockIdKeyReleased

    }//GEN-LAST:event_jTextFieldStockIdKeyReleased

    private void jTextFieldStockIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldStockIdKeyTyped

    }//GEN-LAST:event_jTextFieldStockIdKeyTyped

    private void jTextFieldProductNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldProductNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProductNameFocusGained

    private void jTextFieldProductNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldProductNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProductNameFocusLost

    private void jTextFieldProductNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProductNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProductNameKeyReleased

    private void jTextFieldProductNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProductNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProductNameKeyTyped

    private void jTextFieldPricePerUnitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPricePerUnitFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPricePerUnitFocusGained

    private void jTextFieldPricePerUnitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPricePerUnitFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPricePerUnitFocusLost

    private void jTextFieldPricePerUnitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPricePerUnitKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPricePerUnitKeyReleased

    private void jTextFieldPricePerUnitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPricePerUnitKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPricePerUnitKeyTyped

    private void jTextFieldQtyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldQtyFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQtyFocusGained

    private void jTextFieldQtyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldQtyFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQtyFocusLost

    private void jTextFieldQtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQtyKeyReleased

        Double selling_price = 0.0;
        Double qty = 0.0;
        Double totAmt = 0.0;
        String totAmtDb = null;

        if (jTextFieldQty.getText().length() > 0) {

            selling_price = Double.parseDouble(jTextFieldPricePerUnit.getText());
            qty = Double.parseDouble(jTextFieldQty.getText());
            jLabelQty.setText("");
        }

        totAmt = selling_price * qty;

        DecimalFormat df = new DecimalFormat("0.00");
        totAmtDb = df.format(totAmt);

        jTextFieldTotalAmount.setText(totAmtDb);

    }//GEN-LAST:event_jTextFieldQtyKeyReleased

    private void jTextFieldQtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQtyKeyTyped

        char c = evt.getKeyChar();
        if (!(c >= '0' & c <= '9')) {
            evt.consume();
        }
        
    }//GEN-LAST:event_jTextFieldQtyKeyTyped

    private void jTextFieldTotalAmountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTotalAmountFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalAmountFocusGained

    private void jTextFieldTotalAmountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTotalAmountFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalAmountFocusLost

    private void jTextFieldTotalAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTotalAmountKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalAmountKeyReleased

    private void jTextFieldTotalAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTotalAmountKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalAmountKeyTyped

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked

//        jTextFieldSupplierId.setText(FrameViewSupplierStock.id_Supplier);
//        jTextFieldSupplierName.setText(FrameViewSupplierStock.supplierName);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered

        
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jTextFieldRefNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldRefNoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRefNoFocusGained

    private void jTextFieldRefNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldRefNoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRefNoFocusLost

    private void jTextFieldRefNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRefNoKeyReleased

        String s = jTextFieldRefNo.getText();
        jTextFieldRefNo.setText(s.toUpperCase());
    }//GEN-LAST:event_jTextFieldRefNoKeyReleased

    private void jTextFieldRefNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRefNoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRefNoKeyTyped
String id_product=null;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if ( jComboBoxSupplier.getSelectedIndex()==0 || jComboBoxProductCode.getSelectedIndex()==0 || jTextFieldProductName.getText().length() == 0 || jTextFieldPricePerUnit.getText().length() == 0
                || jTextFieldQty.getText().length() == 0 || jTextFieldCost.getText().length() == 0 ) {
            
            if (jTextFieldCost.getText().length() == 0) {
                jLabelCost.setText("Required");
            }
            
            if (jComboBoxSupplier.getSelectedIndex()==0) {
                jLabelSupplierId.setText("Required");
            }
            
            if (jComboBoxProductCode.getSelectedIndex()==0) {
                jLabelProductCode.setText("Required");
            }
            
            if (jTextFieldProductName.getText().length() == 0) {
                jLabelProductName.setText("Required");
            }
            
            if (jTextFieldPricePerUnit.getText().length() == 0) {
                jLabelPricePerUnit.setText("Required");
            }
            
            if (jTextFieldQty.getText().length() == 0) {
                jLabelQty.setText("Required");
            }
            

        } else {
            
            DecimalFormat df = new DecimalFormat("0.00");
            String costText = df.format(Double.parseDouble(jTextFieldCost.getText()));
            jTextFieldCost.setText(costText);

            AccessPoint ap = new AccessPoint();
            String status = ap.acceesPoint_02(USER_NAME);

            if (status.equals("true")) {

                int s = JOptionPane.showConfirmDialog(null, "Are you sure, you want to update?");

                if (s == JOptionPane.OK_OPTION) {


                    Stock s1 = new Stock();
                    s1.update(jTextFieldDate.getText(), id_product, idSupplier);
                    
                    this.dispose();
                    FrameStockUpdate su = new FrameStockUpdate(LOACATION_ID, USER_NAME);
                    su.setVisible(true);

                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "This access is not grant you\nCan't update details.");

            }
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String s, s1 = null;
        if (jTextFieldRefNo.getText().length() > 0) {
            s = jTextFieldRefNo.getText();
            s1 = s.substring(0, 2);
        }

        if (jTextFieldRefNo.getText().length() == 0) {
            jLabelRef.setText("Required");
        } else if (jTextFieldRefNo.getText().length() > 0 && s1.equals("SE")) {
            
            Stock s2 = new Stock();
            id_product =s2.searchFrameStockUpdate();
            
            jButton1.setEnabled(true);
            
            jTextFieldRefNo.setEnabled(false);
        } else if (jTextFieldRefNo.getText().length() > 0 && s1 != "SE") {
            JOptionPane.showMessageDialog(rootPane, "Please check the reference code");
        } else {
            JOptionPane.showMessageDialog(rootPane, "No data available");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQtyActionPerformed

        Double selling_price = 0.0;
        Double qty = 0.0;
        Double totAmt = 0.0;
        String totAmtDb = null;

        if (jTextFieldQty.getText().length() > 0) {

            selling_price = Double.parseDouble(jTextFieldPricePerUnit.getText());
            qty = Double.parseDouble(jTextFieldQty.getText());
            jLabelQty.setText("");
        }

        totAmt = selling_price * qty;

        DecimalFormat df = new DecimalFormat("0.00");
        totAmtDb = df.format(totAmt);

        jTextFieldTotalAmount.setText(totAmtDb);
        
    }//GEN-LAST:event_jTextFieldQtyActionPerformed

String P_Code=null;
    private void jComboBoxProductCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProductCodeActionPerformed

        if ( jComboBoxSupplier.getSelectedIndex()>0 || jComboBoxProductCode.getSelectedIndex()>0 || jTextFieldProductName.getText().length() > 0 || jTextFieldPricePerUnit.getText().length() > 0
                || jTextFieldQty.getText().length() > 0 || jTextFieldCost.getText().length() > 0) {
            
            if (jTextFieldCost.getText().length() > 0) {
                jLabelCost.setText("");
            }
            
            if (jComboBoxSupplier.getSelectedIndex()>0) {
                jLabelSupplierId.setText("");
            }
            
            if (jComboBoxProductCode.getSelectedIndex()>0) {
                jLabelProductCode.setText("");
            }
            
            if (jTextFieldProductName.getText().length() > 0) {
                jLabelProductName.setText("");
            }
            
            if (jTextFieldPricePerUnit.getText().length() > 0) {
                jLabelPricePerUnit.setText("");
            }
            
            if (jTextFieldQty.getText().length() > 0) {
                jLabelQty.setText("");
            }
           
        }
        
        try {

            ResultSet rs = cls.db.myConnection().createStatement().executeQuery("SELECT * FROM product WHERE p_code='" + jComboBoxProductCode.getSelectedItem().toString() + "'");

            while (rs.next()) {

                jTextFieldProductName.setText(rs.getString("p_name"));
                jTextFieldPricePerUnit.setText(rs.getString("selling_price"));
                P_Code = rs.getString("p_code");
                id_product = rs.getString("idproduct");

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }

    }//GEN-LAST:event_jComboBoxProductCodeActionPerformed

    private void jTextFieldCostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCostKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCostKeyReleased

    private void jTextFieldCostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCostKeyTyped

        char c = evt.getKeyChar();
        if (!(c >= '0' & c <= '9' || c == '.')) {
            evt.consume();
        }

    }//GEN-LAST:event_jTextFieldCostKeyTyped

    private void jComboBoxSupplierFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxSupplierFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSupplierFocusGained

    private void jComboBoxSupplierFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxSupplierFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSupplierFocusLost
public String idSupplier=null;
    private void jComboBoxSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSupplierActionPerformed

        String s = jComboBoxSupplier.getSelectedItem().toString();

        idSupplier = s.substring(0, 4).toString();
        System.out.println(idSupplier);
        
        if (jComboBoxSupplier.getSelectedIndex()>0) {
            jLabelSupplierId.setText("");
        } else {
            jLabelSupplierId.setText("Required");
        }
    }//GEN-LAST:event_jComboBoxSupplierActionPerformed

    private void jTextFieldDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDateFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateFocusGained

    private void jTextFieldDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDateFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateFocusLost

    private void jTextFieldDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDateKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateKeyReleased

    private void jTextFieldDateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDateKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateKeyTyped

    private void jTableimeiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableimeiMouseClicked

    }//GEN-LAST:event_jTableimeiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameStockUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameStockUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameStockUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameStockUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameStockUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public static javax.swing.JComboBox jComboBoxProductCode;
    public static javax.swing.JComboBox jComboBoxSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    public static javax.swing.JLabel jLabelCost;
    private javax.swing.JLabel jLabelDate;
    public static javax.swing.JLabel jLabelPricePerUnit;
    public static javax.swing.JLabel jLabelProductCode;
    public static javax.swing.JLabel jLabelProductName;
    private javax.swing.JLabel jLabelQty;
    public static javax.swing.JLabel jLabelRef;
    public static javax.swing.JLabel jLabelSupplierId;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTable jTableimei;
    public static javax.swing.JTextArea jTextAreaDiscription;
    public static javax.swing.JTextField jTextFieldCost;
    public static javax.swing.JTextField jTextFieldDate;
    public static javax.swing.JTextField jTextFieldPricePerUnit;
    public static javax.swing.JTextField jTextFieldProductName;
    public static javax.swing.JTextField jTextFieldQty;
    public static javax.swing.JTextField jTextFieldRefNo;
    public static javax.swing.JTextField jTextFieldStockId;
    public static javax.swing.JTextField jTextFieldTotalAmount;
    // End of variables declaration//GEN-END:variables
}
