/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import cls.AccessPoint;
import cls.Supplier;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author esh
 */
public class FrameSupplier extends javax.swing.JFrame {

    String LOACATION_ID = null;
    String USER_NAME = null;

    /**
     * Creates new form FrameCategory
     */
    public FrameSupplier() {
        initComponents();
    }

    public FrameSupplier(String LOCATIONID, String USERNAME) {
        initComponents();

        LOACATION_ID = LOCATIONID;
        USER_NAME = USERNAME;

        Supplier s = new Supplier();
        s.loadCountry();

        jButtonUpdate.setEnabled(false);
        jCheckBox.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldSupplierCode = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldSupplierName = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jButtonView = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jComboBoxCountry = new javax.swing.JComboBox();
        jTextFieldMobile1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextFieldMobile2 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextFieldFax = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextFieldCompanyName = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextFieldAdd1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jTextFieldAdd2 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jTextFieldAdd3 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextFieldPhone = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTextFieldBranch = new javax.swing.JTextField();
        jButtonUpdate = new javax.swing.JButton();
        jLabelSupplierCode = new javax.swing.JLabel();
        jLabelSupplierName = new javax.swing.JLabel();
        jLabelCountry = new javax.swing.JLabel();
        jLabelAdd1 = new javax.swing.JLabel();
        jLabelAdd2 = new javax.swing.JLabel();
        jLabelPhone = new javax.swing.JLabel();
        jLabelMobile1 = new javax.swing.JLabel();
        jLabelCompanyName = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaIntials = new javax.swing.JTextArea();
        jLabel32 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jTextFieldLastName = new javax.swing.JTextField();
        jLabelLastName = new javax.swing.JLabel();
        jLabelIntials = new javax.swing.JLabel();
        jCheckBox = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Supplier Creation");
        setPreferredSize(new java.awt.Dimension(800, 520));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Supplier Creation*");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Supplier Code*");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jTextFieldSupplierCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldSupplierCodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSupplierCodeFocusLost(evt);
            }
        });
        jTextFieldSupplierCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSupplierCodeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSupplierCodeKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldSupplierCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 210, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Supplier Name*");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        jTextFieldSupplierName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldSupplierNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSupplierNameFocusLost(evt);
            }
        });
        jTextFieldSupplierName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSupplierNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSupplierNameKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldSupplierName, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 210, -1));

        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save1.png"))); // NOI18N
        jButtonSave.setContentAreaFilled(false);
        jButtonSave.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save2.png"))); // NOI18N
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, 74, 30));

        jButtonView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/view all1.png"))); // NOI18N
        jButtonView.setContentAreaFilled(false);
        jButtonView.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/view all2.png"))); // NOI18N
        jButtonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonView, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 74, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("Country*");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jComboBoxCountry.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBoxCountryFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxCountryFocusLost(evt);
            }
        });
        jComboBoxCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCountryActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 207, 22));

        jTextFieldMobile1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldMobile1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldMobile1FocusLost(evt);
            }
        });
        jTextFieldMobile1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldMobile1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMobile1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldMobile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 210, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("Mobile No 1*");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText("Mobile No 2");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));

        jTextFieldMobile2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldMobile2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldMobile2FocusLost(evt);
            }
        });
        jTextFieldMobile2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldMobile2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMobile2KeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldMobile2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 210, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setText("Fax No");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, -1, -1));

        jTextFieldFax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldFaxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldFaxFocusLost(evt);
            }
        });
        jTextFieldFax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldFaxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFaxKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldFax, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 210, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setText("E-mail");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jTextFieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEmailFocusLost(evt);
            }
        });
        jTextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 210, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setText("Company Name*");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jTextFieldCompanyName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldCompanyNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCompanyNameFocusLost(evt);
            }
        });
        jTextFieldCompanyName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCompanyNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCompanyNameKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 210, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel33.setText("Address Line 1*");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));

        jTextFieldAdd1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldAdd1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldAdd1FocusLost(evt);
            }
        });
        jTextFieldAdd1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldAdd1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAdd1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 210, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel34.setText("Address Line 2*");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jTextFieldAdd2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldAdd2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldAdd2FocusLost(evt);
            }
        });
        jTextFieldAdd2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldAdd2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAdd2KeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 210, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel35.setText("Address Line 3");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, -1));

        jTextFieldAdd3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldAdd3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldAdd3FocusLost(evt);
            }
        });
        jTextFieldAdd3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldAdd3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAdd3KeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldAdd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 210, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel36.setText("Phone No*");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jTextFieldPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPhoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPhoneFocusLost(evt);
            }
        });
        jTextFieldPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPhoneKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPhoneKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 210, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel37.setText("Branch");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, -1, -1));

        jTextFieldBranch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldBranchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldBranchFocusLost(evt);
            }
        });
        jTextFieldBranch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBranchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBranchKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 210, -1));

        jButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update1.png"))); // NOI18N
        jButtonUpdate.setContentAreaFilled(false);
        jButtonUpdate.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update2.png"))); // NOI18N
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 74, 30));

        jLabelSupplierCode.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSupplierCode.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelSupplierCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 200, 15));

        jLabelSupplierName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSupplierName.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelSupplierName, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 200, 15));

        jLabelCountry.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCountry.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 200, 15));

        jLabelAdd1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAdd1.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 200, 15));

        jLabelAdd2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAdd2.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 200, 15));

        jLabelPhone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPhone.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 200, 15));

        jLabelMobile1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMobile1.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelMobile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 200, 15));

        jLabelCompanyName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCompanyName.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 200, 15));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh1.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 74, 30));

        jTextAreaIntials.setEditable(false);
        jTextAreaIntials.setColumns(20);
        jTextAreaIntials.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextAreaIntials.setRows(1);
        jTextAreaIntials.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextAreaIntialsKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTextAreaIntials);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 207, 22));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel32.setText("Intials *");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel38.setText("Last Name *");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        jTextFieldLastName.setEditable(false);
        jTextFieldLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldLastNameKeyReleased(evt);
            }
        });
        jPanel1.add(jTextFieldLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 207, 22));

        jLabelLastName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLastName.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 200, 15));

        jLabelIntials.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelIntials.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelIntials, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 200, 15));

        jCheckBox.setContentAreaFilled(false);
        jPanel1.add(jCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 413, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search1.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, 74, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Inactive.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 410, 74, 26));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSupplierCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSupplierCodeFocusGained

    }//GEN-LAST:event_jTextFieldSupplierCodeFocusGained
    String id_Supplier = null;
    private void jTextFieldSupplierCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSupplierCodeFocusLost

        Supplier s = new Supplier();
        id_Supplier = s.searchTextField();

        if (id_Supplier != null) {
            JOptionPane.showMessageDialog(rootPane, "Supplier code already used");
            jButtonSave.setEnabled(false);
            jButtonUpdate.setEnabled(true);
            jCheckBox.setVisible(true);
            jTextFieldSupplierCode.setEnabled(false);
        }

    }//GEN-LAST:event_jTextFieldSupplierCodeFocusLost

    private void jTextFieldSupplierCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSupplierCodeKeyReleased

        String s = jTextFieldSupplierCode.getText();
        jTextFieldSupplierCode.setText(s.toUpperCase());

        jLabelSupplierCode.setText("");
    }//GEN-LAST:event_jTextFieldSupplierCodeKeyReleased

    private void jTextFieldSupplierCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSupplierCodeKeyTyped

    }//GEN-LAST:event_jTextFieldSupplierCodeKeyTyped

    private void jTextFieldSupplierNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSupplierNameFocusGained

        jTextAreaIntials.setText("");
        jTextFieldLastName.setText("");
    }//GEN-LAST:event_jTextFieldSupplierNameFocusGained
    String name_initials = null;
    private void jTextFieldSupplierNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSupplierNameFocusLost

        jTextFieldMobile1.grabFocus();

        String s = jTextFieldSupplierName.getText();

        jLabelSupplierName.setText("");

        String[] arr = s.split(" ");
        // print all the initials
        for (int i = 0; i < arr.length - 1; i++) {

            jTextAreaIntials.append(arr[i].charAt(0) + ".");
        }
        // print the last name
        jTextFieldLastName.setText(arr[arr.length - 1]);

        try {

            name_initials = jTextAreaIntials.getText() + jTextFieldLastName.getText();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e + "\nPlease contact the system administrator");
            this.dispose();
        }

    }//GEN-LAST:event_jTextFieldSupplierNameFocusLost

    private void jTextFieldSupplierNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSupplierNameKeyReleased

        jLabelIntials.setText("");
        jLabelLastName.setText("");
        jLabelSupplierName.setText("");

        String s = jTextFieldSupplierName.getText();
        jTextFieldSupplierName.setText(s.toUpperCase());
    }//GEN-LAST:event_jTextFieldSupplierNameKeyReleased

    private void jTextFieldSupplierNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSupplierNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSupplierNameKeyTyped

    private void jComboBoxCountryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxCountryFocusGained

    }//GEN-LAST:event_jComboBoxCountryFocusGained

    private void jComboBoxCountryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxCountryFocusLost

    }//GEN-LAST:event_jComboBoxCountryFocusLost
    String id_country = null;
    private void jComboBoxCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCountryActionPerformed

        if (jComboBoxCountry.getSelectedIndex() > 0) {
            jLabelCountry.setText("");

            try {

                ResultSet rs = cls.db.myConnection().createStatement().executeQuery("SELECT * FROM country WHERE country_name='" + jComboBoxCountry.getSelectedItem().toString() + "' ");

                while (rs.next()) {
                    id_country = rs.getString("idcountry");
                }

            } catch (Exception e) {

                e.printStackTrace();
                JOptionPane.showMessageDialog(null, e);
            }

        }
    }//GEN-LAST:event_jComboBoxCountryActionPerformed

    private void jTextFieldMobile1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldMobile1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMobile1FocusGained

    private void jTextFieldMobile1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldMobile1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMobile1FocusLost

    private void jTextFieldMobile1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMobile1KeyReleased

        jLabelMobile1.setText("");

    }//GEN-LAST:event_jTextFieldMobile1KeyReleased

    private void jTextFieldMobile1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMobile1KeyTyped

        char c = evt.getKeyChar();
        if (!(c >= '0' & c <= '9')) {
            evt.consume();
        }

        if (jTextFieldMobile1.getText().length() > 9) {
            evt.consume();
        }

    }//GEN-LAST:event_jTextFieldMobile1KeyTyped

    private void jTextFieldMobile2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldMobile2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMobile2FocusGained

    private void jTextFieldMobile2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldMobile2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMobile2FocusLost

    private void jTextFieldMobile2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMobile2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMobile2KeyReleased

    private void jTextFieldMobile2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMobile2KeyTyped

        char c = evt.getKeyChar();
        if (!(c >= '0' & c <= '9')) {
            evt.consume();
        }

        if (jTextFieldMobile2.getText().length() > 9) {
            evt.consume();
        }

    }//GEN-LAST:event_jTextFieldMobile2KeyTyped

    private void jTextFieldFaxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFaxFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFaxFocusGained

    private void jTextFieldFaxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFaxFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFaxFocusLost

    private void jTextFieldFaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFaxKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFaxKeyReleased

    private void jTextFieldFaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFaxKeyTyped

        char c = evt.getKeyChar();
        if (!(c >= '0' & c <= '9')) {
            evt.consume();
        }

        if (jTextFieldFax.getText().length() > 9) {
            evt.consume();
        }

    }//GEN-LAST:event_jTextFieldFaxKeyTyped

    private void jTextFieldEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailFocusGained

    private void jTextFieldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailFocusLost

    private void jTextFieldEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailKeyReleased

    private void jTextFieldEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailKeyTyped

    private void jTextFieldCompanyNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCompanyNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCompanyNameFocusGained

    private void jTextFieldCompanyNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCompanyNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCompanyNameFocusLost

    private void jTextFieldCompanyNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCompanyNameKeyReleased

        jLabelCompanyName.setText("");

        String s = jTextFieldCompanyName.getText();
        jTextFieldCompanyName.setText(s.toUpperCase());

    }//GEN-LAST:event_jTextFieldCompanyNameKeyReleased

    private void jTextFieldCompanyNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCompanyNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCompanyNameKeyTyped

    private void jTextFieldAdd1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAdd1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAdd1FocusGained

    private void jTextFieldAdd1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAdd1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAdd1FocusLost

    private void jTextFieldAdd1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAdd1KeyReleased

        jLabelAdd1.setText("");

        String s = jTextFieldAdd1.getText();
        jTextFieldAdd1.setText(s.toUpperCase());

    }//GEN-LAST:event_jTextFieldAdd1KeyReleased

    private void jTextFieldAdd1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAdd1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAdd1KeyTyped

    private void jTextFieldAdd2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAdd2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAdd2FocusGained

    private void jTextFieldAdd2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAdd2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAdd2FocusLost

    private void jTextFieldAdd2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAdd2KeyReleased

        jLabelAdd2.setText("");

        String s = jTextFieldAdd2.getText();
        jTextFieldAdd2.setText(s.toUpperCase());

    }//GEN-LAST:event_jTextFieldAdd2KeyReleased

    private void jTextFieldAdd2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAdd2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAdd2KeyTyped

    private void jTextFieldAdd3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAdd3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAdd3FocusGained

    private void jTextFieldAdd3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAdd3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAdd3FocusLost

    private void jTextFieldAdd3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAdd3KeyReleased

        String s = jTextFieldAdd3.getText();
        jTextFieldAdd3.setText(s.toUpperCase());

    }//GEN-LAST:event_jTextFieldAdd3KeyReleased

    private void jTextFieldAdd3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAdd3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAdd3KeyTyped

    private void jTextFieldPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPhoneFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneFocusGained

    private void jTextFieldPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPhoneFocusLost

        jButtonSave.grabFocus();
    }//GEN-LAST:event_jTextFieldPhoneFocusLost

    private void jTextFieldPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPhoneKeyReleased

        jLabelPhone.setText("");

    }//GEN-LAST:event_jTextFieldPhoneKeyReleased

    private void jTextFieldPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPhoneKeyTyped

        char c = evt.getKeyChar();
        if (!(c >= '0' & c <= '9')) {
            evt.consume();
        }

        if (jTextFieldPhone.getText().length() > 9) {
            evt.consume();
        }

    }//GEN-LAST:event_jTextFieldPhoneKeyTyped

    private void jTextFieldBranchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBranchFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBranchFocusGained

    private void jTextFieldBranchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBranchFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBranchFocusLost

    private void jTextFieldBranchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBranchKeyReleased

        String s = jTextFieldBranch.getText();
        jTextFieldBranch.setText(s.toUpperCase());

    }//GEN-LAST:event_jTextFieldBranchKeyReleased

    private void jTextFieldBranchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBranchKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBranchKeyTyped

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed

        if (jTextFieldSupplierCode.getText().length() == 0 || jTextFieldSupplierName.getText().length() == 0 || jTextFieldAdd1.getText().length() == 0
                || jTextFieldAdd2.getText().length() == 0 || jTextFieldPhone.getText().length() == 0 || jTextFieldMobile1.getText().length() == 0
                || jTextFieldCompanyName.getText().length() == 0 || jComboBoxCountry.getSelectedIndex() == 0
                || jTextAreaIntials.getText().length() == 0 || jTextFieldLastName.getText().length() == 0) {

            if (jTextFieldSupplierCode.getText().length() == 0) {
                jLabelSupplierCode.setText("Required");
            }

            if (jTextFieldSupplierName.getText().length() == 0) {
                jLabelSupplierName.setText("Required");
            }

            if (jTextFieldAdd1.getText().length() == 0) {
                jLabelAdd1.setText("Required");
            }

            if (jTextFieldAdd2.getText().length() == 0) {
                jLabelAdd2.setText("Required");
            }

            if (jTextFieldPhone.getText().length() == 0) {
                jLabelPhone.setText("Required");
            }

            if (jTextFieldMobile1.getText().length() == 0) {
                jLabelMobile1.setText("Required");
            }

            if (jTextFieldCompanyName.getText().length() == 0) {
                jLabelCompanyName.setText("Required");
            }

            if (jComboBoxCountry.getSelectedIndex() == 0) {
                jLabelCountry.setText("Required");
            }

            if (jTextAreaIntials.getText().length() == 0) {
                jLabelIntials.setText("Required");
            }

            if (jTextFieldLastName.getText().length() == 0) {
                jLabelLastName.setText("Required");
            }

        } else {

            AccessPoint ap = new AccessPoint();
            String status = ap.acceesPoint_01(USER_NAME);

            if (status.equals("true")) {

                int s = JOptionPane.showConfirmDialog(null, "Are you sure, you want to Save?");

                if (s == JOptionPane.OK_OPTION) {

                    Supplier s1 = new Supplier();
                    s1.save(id_country, name_initials);

                    this.dispose();
                    FrameSupplier s2 = new FrameSupplier(LOACATION_ID, USER_NAME);
                    s2.setVisible(true);
                }

            } else {
                jButtonUpdate.setVisible(false);
                JOptionPane.showMessageDialog(rootPane, "This access is not grant you\nCan't save details.");

            }

        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.dispose();
        FrameSupplier s2 = new FrameSupplier(LOACATION_ID, USER_NAME);
        s2.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewActionPerformed

        FrameViewSupplier vs = new FrameViewSupplier(LOACATION_ID, USER_NAME);
        vs.setVisible(true);
    }//GEN-LAST:event_jButtonViewActionPerformed

    private void jTextAreaIntialsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaIntialsKeyReleased

    }//GEN-LAST:event_jTextAreaIntialsKeyReleased

    private void jTextFieldLastNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLastNameKeyReleased

    }//GEN-LAST:event_jTextFieldLastNameKeyReleased

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed

        if (jTextFieldSupplierCode.getText().length() == 0 || jTextFieldSupplierName.getText().length() == 0 || jTextFieldAdd1.getText().length() == 0
                || jTextFieldAdd2.getText().length() == 0 || jTextFieldPhone.getText().length() == 0 || jTextFieldMobile1.getText().length() == 0
                || jTextFieldCompanyName.getText().length() == 0 || jComboBoxCountry.getSelectedIndex() == 0
                || jTextAreaIntials.getText().length() == 0 || jTextFieldLastName.getText().length() == 0) {

            if (jTextFieldSupplierCode.getText().length() == 0) {
                jLabelSupplierCode.setText("Required");
            }

            if (jTextFieldSupplierName.getText().length() == 0) {
                jLabelSupplierName.setText("Required");
            }

            if (jTextFieldAdd1.getText().length() == 0) {
                jLabelAdd1.setText("Required");
            }

            if (jTextFieldAdd2.getText().length() == 0) {
                jLabelAdd2.setText("Required");
            }

            if (jTextFieldPhone.getText().length() == 0) {
                jLabelPhone.setText("Required");
            }

            if (jTextFieldMobile1.getText().length() == 0) {
                jLabelMobile1.setText("Required");
            }

            if (jTextFieldCompanyName.getText().length() == 0) {
                jLabelCompanyName.setText("Required");
            }

            if (jComboBoxCountry.getSelectedIndex() == 0) {
                jLabelCountry.setText("Required");
            }

            if (jTextAreaIntials.getText().length() == 0) {
                jLabelIntials.setText("Required");
            }

            if (jTextFieldLastName.getText().length() == 0) {
                jLabelLastName.setText("Required");
            }

        } else {

            AccessPoint ap = new AccessPoint();
            String status = ap.acceesPoint_02(USER_NAME);

            if (status.equals("true")) {

                int s = JOptionPane.showConfirmDialog(null, "Are you sure you want to update?");

                if (s == JOptionPane.OK_OPTION) {

                    Supplier s2 = new Supplier();
                    s2.update(id_country, name_initials, id_Supplier);

                    this.dispose();
                    FrameSupplier s3 = new FrameSupplier(LOACATION_ID, USER_NAME);
                    s3.setVisible(true);

                }

            } else {
                jButtonUpdate.setVisible(false);
                JOptionPane.showMessageDialog(rootPane, "This access is not grant you\nCan't update details.");

            }

        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (jTextFieldSupplierCode.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Please input the supplier code");
        } else {

            Supplier s = new Supplier();
            id_Supplier = s.searchTextField();

            if (id_Supplier != null) {
                JOptionPane.showMessageDialog(rootPane, "Supplier code already used");
                jButtonSave.setEnabled(false);
                jButtonUpdate.setEnabled(true);
                jCheckBox.setVisible(true);
                jTextFieldSupplierCode.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameSupplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JButton jButtonView;
    public static javax.swing.JCheckBox jCheckBox;
    public static javax.swing.JComboBox jComboBoxCountry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabelAdd1;
    private javax.swing.JLabel jLabelAdd2;
    private javax.swing.JLabel jLabelCompanyName;
    private javax.swing.JLabel jLabelCountry;
    private javax.swing.JLabel jLabelIntials;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelMobile1;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelSupplierCode;
    private javax.swing.JLabel jLabelSupplierName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea jTextAreaIntials;
    public static javax.swing.JTextField jTextFieldAdd1;
    public static javax.swing.JTextField jTextFieldAdd2;
    public static javax.swing.JTextField jTextFieldAdd3;
    public static javax.swing.JTextField jTextFieldBranch;
    public static javax.swing.JTextField jTextFieldCompanyName;
    public static javax.swing.JTextField jTextFieldEmail;
    public static javax.swing.JTextField jTextFieldFax;
    public static javax.swing.JTextField jTextFieldLastName;
    public static javax.swing.JTextField jTextFieldMobile1;
    public static javax.swing.JTextField jTextFieldMobile2;
    public static javax.swing.JTextField jTextFieldPhone;
    public static javax.swing.JTextField jTextFieldSupplierCode;
    public static javax.swing.JTextField jTextFieldSupplierName;
    // End of variables declaration//GEN-END:variables
}
