/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import cls.AccessPoint;
import cls.Product;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author esh
 */
public class FrameProductEntry extends javax.swing.JFrame {

    String LOACATION_ID = null;
    String USER_NAME = null;

    String CURRENT_DATE = null;
    DefaultTableModel dtm = new DefaultTableModel();

    /**
     * Creates new form FrameCategory
     */
    public FrameProductEntry() {
        initComponents();
    }

    public FrameProductEntry(String LOCATIONID, String USERNAME) {
        initComponents();

        LOACATION_ID = LOCATIONID;
        USER_NAME = USERNAME;

        Product p = new Product();
        p.loadCategory();
        loadSupplier();

        showCurrentDate();

        AutoCompleteDecorator.decorate(jComboBoxSupplier);
    }

    void showCurrentDate() {

        
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                Date d = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                        CURRENT_DATE=(sdf.format(d));
            }
        }).start();
        
    }

    void loadSupplier() {

        try {

            ResultSet rs = cls.db.myConnection().createStatement().executeQuery("SELECT * FROM supplier WHERE status='" + "ACTIVE" + "' ");

            Vector v = new Vector();

            v.add("--SELECT--");
            while (rs.next()) {

                String idSupplier = rs.getString("idsupplier");
                String fullname = rs.getString("supplier_name");
                String setName = idSupplier + " - " + fullname;
                v.add(setName);

            }

            jComboBoxSupplier.setModel(new DefaultComboBoxModel(v));

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldProductCode = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldProductName = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jComboBoxCategoryName = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        jComboBoxSubCategory = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDiscription = new javax.swing.JTextArea();
        jTextFieldCost = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextFieldSellingPrice = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextFieldOPStock = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextFieldDiscount = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextFieldVat = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabelCost = new javax.swing.JLabel();
        jLabelProductName = new javax.swing.JLabel();
        jLabelCategoryName = new javax.swing.JLabel();
        jLabelSupplier = new javax.swing.JLabel();
        jLabelSubCategory = new javax.swing.JLabel();
        jLabelProductCode = new javax.swing.JLabel();
        jLabelSellingPrice = new javax.swing.JLabel();
        jLabelOPStock = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextFieldStockId = new javax.swing.JTextField();
        jButtonRefresh = new javax.swing.JButton();
        jButtonView = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jComboBoxSupplier = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel34 = new javax.swing.JLabel();
        jComboBoxType = new javax.swing.JComboBox();
        jTextFieldIMEI1 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jTextFieldIMEI2 = new javax.swing.JTextField();
        jLabelIMEI1 = new javax.swing.JLabel();
        jLabelIMEI2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Product Entry");
        setResizable(false);

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add1.png"))); // NOI18N
        jButtonAdd.setContentAreaFilled(false);
        jButtonAdd.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add2.png"))); // NOI18N
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 480, 74, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Product Entry");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Product Code*");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jTextFieldProductCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldProductCodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldProductCodeFocusLost(evt);
            }
        });
        jTextFieldProductCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldProductCodeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldProductCodeKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldProductCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 210, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Product Name*");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        jTextFieldProductName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldProductNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldProductNameFocusLost(evt);
            }
        });
        jTextFieldProductName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldProductNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldProductNameKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 210, -1));

        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save1.png"))); // NOI18N
        jButtonSave.setContentAreaFilled(false);
        jButtonSave.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save2.png"))); // NOI18N
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 660, 74, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("Category Name*");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        jComboBoxCategoryName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBoxCategoryNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxCategoryNameFocusLost(evt);
            }
        });
        jComboBoxCategoryName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoryNameActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxCategoryName, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 207, 22));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("Sub Category Name*");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jComboBoxSubCategory.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBoxSubCategoryFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxSubCategoryFocusLost(evt);
            }
        });
        jComboBoxSubCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSubCategoryActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxSubCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 207, 22));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("Discription");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jTextAreaDiscription.setColumns(20);
        jTextAreaDiscription.setRows(5);
        jTextAreaDiscription.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextAreaDiscriptionFocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(jTextAreaDiscription);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 210, 80));

        jTextFieldCost.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldCostFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCostFocusLost(evt);
            }
        });
        jTextFieldCost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCostKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCostKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 210, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("Cost*");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText("Selling Price*");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        jTextFieldSellingPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldSellingPriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSellingPriceFocusLost(evt);
            }
        });
        jTextFieldSellingPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSellingPriceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSellingPriceKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldSellingPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 210, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setText("Opening Stock*");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jTextFieldOPStock.setEditable(false);
        jTextFieldOPStock.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldOPStockFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldOPStockFocusLost(evt);
            }
        });
        jTextFieldOPStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldOPStockKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldOPStockKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldOPStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 210, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setText("Discount %");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        jTextFieldDiscount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDiscountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDiscountFocusLost(evt);
            }
        });
        jTextFieldDiscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldDiscountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDiscountKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 210, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setText("Vat %");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        jTextFieldVat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldVatFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldVatFocusLost(evt);
            }
        });
        jTextFieldVat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldVatKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldVatKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldVat, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 210, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel32.setText("Supplier*");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabelCost.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCost.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 200, 15));

        jLabelProductName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelProductName.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 200, 15));

        jLabelCategoryName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCategoryName.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelCategoryName, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 200, 15));

        jLabelSupplier.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSupplier.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 210, 15));

        jLabelSubCategory.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSubCategory.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelSubCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 200, 15));

        jLabelProductCode.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelProductCode.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelProductCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 200, 15));

        jLabelSellingPrice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSellingPrice.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelSellingPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 200, 15));

        jLabelOPStock.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelOPStock.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelOPStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 200, 15));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel33.setText("Stock ID");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        jTextFieldStockId.setEditable(false);
        jTextFieldStockId.setText("01");
        jTextFieldStockId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldStockIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldStockIdFocusLost(evt);
            }
        });
        jTextFieldStockId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldStockIdKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldStockIdKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldStockId, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 210, -1));

        jButtonRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh1.png"))); // NOI18N
        jButtonRefresh.setContentAreaFilled(false);
        jButtonRefresh.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh2.png"))); // NOI18N
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, 74, 30));

        jButtonView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/view all1.png"))); // NOI18N
        jButtonView.setContentAreaFilled(false);
        jButtonView.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/view all2.png"))); // NOI18N
        jButtonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonView, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 660, 74, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update1.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 660, 74, 30));

        jComboBoxSupplier.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBoxSupplierFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxSupplierFocusLost(evt);
            }
        });
        jComboBoxSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSupplierActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 207, 22));

        jButton2.setText("Create New Supplier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, -1));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PRODUCT", "IMEI 1", "IMEI 2", "REMOVE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(20);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(3).setMinWidth(100);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 750, 130));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel34.setText("Type");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PHONE", "OTHER" }));
        jComboBoxType.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBoxTypeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxTypeFocusLost(evt);
            }
        });
        jComboBoxType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTypeActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxType, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 207, 22));

        jTextFieldIMEI1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldIMEI1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldIMEI1FocusLost(evt);
            }
        });
        jTextFieldIMEI1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldIMEI1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIMEI1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldIMEI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 210, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel35.setText("IMEI 1*");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel36.setText("IMEI 2*");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, -1, -1));

        jTextFieldIMEI2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldIMEI2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldIMEI2FocusLost(evt);
            }
        });
        jTextFieldIMEI2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldIMEI2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIMEI2KeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldIMEI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 210, -1));

        jLabelIMEI1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelIMEI1.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelIMEI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 210, 15));

        jLabelIMEI2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelIMEI2.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelIMEI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 210, 15));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldProductCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldProductCodeFocusGained

    }//GEN-LAST:event_jTextFieldProductCodeFocusGained
    String id_product = null;
    private void jTextFieldProductCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldProductCodeFocusLost

        Product p = new Product();
        id_product = p.search();

        if (id_product != null) {
            JOptionPane.showMessageDialog(rootPane, "Product code already used");
            jButtonSave.setEnabled(false);
            jTextFieldProductCode.setEnabled(false);
            jTextAreaDiscription.setEnabled(false);
            jTextFieldCost.setEnabled(false);
            jTextFieldDiscount.setEnabled(false);
            jTextFieldOPStock.setEnabled(false);
            jTextFieldProductCode.setEnabled(false);
            jTextFieldProductName.setEnabled(false);
            jTextFieldSellingPrice.setEnabled(false);
            jTextFieldVat.setEnabled(false);
            jComboBoxCategoryName.setEnabled(false);
            jComboBoxSubCategory.setEnabled(false);

        }

    }//GEN-LAST:event_jTextFieldProductCodeFocusLost

    private void jTextFieldProductCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProductCodeKeyReleased

        String s = jTextFieldProductCode.getText();
        jTextFieldProductCode.setText(s.toUpperCase());

        jLabelProductCode.setText("");
        dtm.setRowCount(0);
        jTextFieldOPStock.setText("");
        char c = evt.getKeyChar();
        if (c == evt.VK_BACK_SPACE) {
            dtm.setRowCount(0);
            jTextFieldOPStock.setText("");
        }
    }//GEN-LAST:event_jTextFieldProductCodeKeyReleased

    private void jTextFieldProductCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProductCodeKeyTyped

    }//GEN-LAST:event_jTextFieldProductCodeKeyTyped

    private void jTextFieldProductNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldProductNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProductNameFocusGained

    private void jTextFieldProductNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldProductNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProductNameFocusLost

    private void jTextFieldProductNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProductNameKeyReleased

        String s = jTextFieldProductName.getText();
        jTextFieldProductName.setText(s.toUpperCase());

        jLabelProductName.setText("");
    }//GEN-LAST:event_jTextFieldProductNameKeyReleased

    private void jTextFieldProductNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProductNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProductNameKeyTyped

    private void jComboBoxCategoryNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxCategoryNameFocusGained

    }//GEN-LAST:event_jComboBoxCategoryNameFocusGained

    private void jComboBoxCategoryNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxCategoryNameFocusLost

    }//GEN-LAST:event_jComboBoxCategoryNameFocusLost
    String id_category = null;
    String id_subCategory = null;
    private void jComboBoxCategoryNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoryNameActionPerformed

        if (jComboBoxCategoryName.getSelectedIndex() > 0) {
            jLabelCategoryName.setText("");

            try {

                ResultSet rs = cls.db.myConnection().createStatement().executeQuery("SELECT * FROM category WHERE category_name='" + jComboBoxCategoryName.getSelectedItem().toString() + "' ");

                while (rs.next()) {
                    id_category = rs.getString("idcategory");

                    ResultSet rs1 = cls.db.myConnection().createStatement().executeQuery("SELECT * FROM sub_category WHERE idcategory='" + id_category + "' ");

                    Vector v = new Vector();
                    v.add("--SELECT --");
                    while (rs1.next()) {
                        v.add(rs1.getString("sub_category_name"));
                    }
                    jComboBoxSubCategory.setModel(new DefaultComboBoxModel(v));
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_jComboBoxCategoryNameActionPerformed

    private void jComboBoxSubCategoryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxSubCategoryFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSubCategoryFocusGained

    private void jComboBoxSubCategoryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxSubCategoryFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSubCategoryFocusLost

    private void jComboBoxSubCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSubCategoryActionPerformed

        if (jComboBoxSubCategory.getSelectedIndex() > 0) {
            jLabelSubCategory.setText("");

            try {

                ResultSet rs = cls.db.myConnection().createStatement().executeQuery("SELECT * FROM sub_category WHERE sub_category_name='" + jComboBoxSubCategory.getSelectedItem().toString() + "' ");

                while (rs.next()) {
                    id_subCategory = rs.getString("idsub_category");
                }

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(rootPane, e);
            }

        }
    }//GEN-LAST:event_jComboBoxSubCategoryActionPerformed

    private void jTextFieldCostFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCostFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCostFocusGained

    private void jTextFieldCostFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCostFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCostFocusLost

    private void jTextFieldCostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCostKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCostKeyReleased

    private void jTextFieldCostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCostKeyTyped

        jLabelCost.setText("");
        char c = evt.getKeyChar();
        if (!(c >= '0' & c <= '9' || c == '.')) {
            evt.consume();
        }

    }//GEN-LAST:event_jTextFieldCostKeyTyped

    private void jTextFieldSellingPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSellingPriceFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSellingPriceFocusGained

    private void jTextFieldSellingPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSellingPriceFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSellingPriceFocusLost

    private void jTextFieldSellingPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSellingPriceKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSellingPriceKeyReleased

    private void jTextFieldSellingPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSellingPriceKeyTyped

        jLabelSellingPrice.setText("");
        char c = evt.getKeyChar();
        if (!(c >= '0' & c <= '9' || c == '.')) {
            evt.consume();
        }

    }//GEN-LAST:event_jTextFieldSellingPriceKeyTyped

    private void jTextFieldOPStockFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldOPStockFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOPStockFocusGained

    private void jTextFieldOPStockFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldOPStockFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOPStockFocusLost

    private void jTextFieldOPStockKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldOPStockKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOPStockKeyReleased

    private void jTextFieldOPStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldOPStockKeyTyped

        jLabelOPStock.setText("");
        char c = evt.getKeyChar();
        if (!(c >= '0' & c <= '9')) {
            evt.consume();
        }

    }//GEN-LAST:event_jTextFieldOPStockKeyTyped

    private void jTextFieldDiscountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDiscountFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDiscountFocusGained

    private void jTextFieldDiscountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDiscountFocusLost

        if (jTextFieldDiscount.getText().length() == 0) {
            jTextFieldDiscount.setText("0.00");
        }
        jTextFieldVat.grabFocus();
    }//GEN-LAST:event_jTextFieldDiscountFocusLost

    private void jTextFieldDiscountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDiscountKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDiscountKeyReleased

    private void jTextFieldDiscountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDiscountKeyTyped

        char c = evt.getKeyChar();
        if (!(c >= '0' & c <= '9' || c == '.')) {
            evt.consume();
        }

        if (jTextFieldDiscount.getText().length() > 4) {
            evt.consume();
        }

    }//GEN-LAST:event_jTextFieldDiscountKeyTyped

    private void jTextFieldVatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldVatFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVatFocusGained

    private void jTextFieldVatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldVatFocusLost

        if (jTextFieldVat.getText().length() == 0) {
            jTextFieldVat.setText("0.00");
        }
        jComboBoxSupplier.grabFocus();
    }//GEN-LAST:event_jTextFieldVatFocusLost

    private void jTextFieldVatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldVatKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVatKeyReleased

    private void jTextFieldVatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldVatKeyTyped

        char c = evt.getKeyChar();
        if (!(c >= '0' & c <= '9' || c == '.')) {
            evt.consume();
        }

        if (jTextFieldVat.getText().length() > 4) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldVatKeyTyped

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed

        Product p = new Product();
        id_product = p.search();

        if (jTextFieldProductCode.getText().length() == 0 || jTextFieldProductName.getText().length() == 0 || jComboBoxCategoryName.getSelectedIndex() == 0
                || jComboBoxSubCategory.getSelectedIndex() <= 0 || jComboBoxSupplier.getSelectedIndex() <= 0  || jTextFieldCost.getText().length() == 0
                || jTextFieldSellingPrice.getText().length() == 0 || jTextFieldOPStock.getText().length() == 0 || jTextFieldOPStock.getText().equals("0") ) {

            if (jTextFieldProductCode.getText().length() == 0) {
                jLabelProductCode.setText("Required");
            }

            if (jTextFieldProductName.getText().length() == 0) {
                jLabelProductName.setText("Required");
            }

            if (jComboBoxCategoryName.getSelectedIndex() == 0) {
                jLabelCategoryName.setText("Required");
            }

            if (jComboBoxSubCategory.getSelectedIndex() <= 0) {
                jLabelSubCategory.setText("Required");
            }
            
            if (jComboBoxSupplier.getSelectedIndex() <= 0) {
                jLabelSupplier.setText("Required");
            }

            if (jTextFieldCost.getText().length() == 0) {
                jLabelCost.setText("Required");
            }

            if (jTextFieldSellingPrice.getText().length() == 0) {
                jLabelSellingPrice.setText("Required");
            }

            if (jTextFieldOPStock.getText().length() == 0) {
                jLabelOPStock.setText("Required");
            }
            
            if (jTextFieldOPStock.getText().equals("0")) {
                jLabelOPStock.setText("Invalid stock amount");
            }

        } else if (id_product != null) {

            JOptionPane.showMessageDialog(rootPane, "Product code already used");
            jButtonSave.setEnabled(false);
            
            jTextFieldProductCode.setEnabled(false);
            jTextAreaDiscription.setEnabled(false);
            jTextFieldCost.setEnabled(false);
            jTextFieldDiscount.setEnabled(false);
            jTextFieldOPStock.setEnabled(false);
            jTextFieldProductCode.setEnabled(false);
            jTextFieldProductName.setEnabled(false);
            jTextFieldSellingPrice.setEnabled(false);
            jTextFieldVat.setEnabled(false);
            jComboBoxCategoryName.setEnabled(false);
            jComboBoxSubCategory.setEnabled(false);

        } else {

            DecimalFormat df = new DecimalFormat("0.00");
            String costText = df.format(Double.parseDouble(jTextFieldCost.getText()));
            jTextFieldCost.setText(costText);

            DecimalFormat df1 = new DecimalFormat("0.00");
            String sellingPriceText = df1.format(Double.parseDouble(jTextFieldSellingPrice.getText()));
            jTextFieldSellingPrice.setText(sellingPriceText);

            AccessPoint ap = new AccessPoint();
            String status = ap.acceesPoint_01(USER_NAME);

            if (jTextFieldDiscount.getText().length() == 0) {
                jTextFieldDiscount.setText("0.00");
            }

            if (jTextFieldVat.getText().length() == 0) {
                jTextFieldVat.setText("0.00");
            }

            if (jTextAreaDiscription.getText().length() == 0) {
                jTextAreaDiscription.setText("NULL");
            }

            if (status.equals("true")) {

                int s = JOptionPane.showConfirmDialog(null, "Are you sure, you want to Save?");

                if (s == JOptionPane.OK_OPTION) {

                    p.save(id_category, id_subCategory, CURRENT_DATE);

                    jTextAreaDiscription.setText("");
                    jTextFieldCost.setText("");
                    jTextFieldDiscount.setText("");
                    jTextFieldOPStock.setText("");
                    jTextFieldProductCode.setText("");
                    jTextFieldProductName.setText("");
                    jTextFieldSellingPrice.setText("");
                    jTextFieldVat.setText("");
                    
                    dtm.setRowCount(0);

                    p.loadCategory();
                    jComboBoxSubCategory.removeAllItems();
                    
                    jTextFieldProductCode.grabFocus();

                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "This access is not grant you\nCan't update details.");

            }

        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jTextFieldStockIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldStockIdFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStockIdFocusGained

    private void jTextFieldStockIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldStockIdFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStockIdFocusLost

    private void jTextFieldStockIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldStockIdKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStockIdKeyReleased

    private void jTextFieldStockIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldStockIdKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStockIdKeyTyped

    private void jButtonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewActionPerformed

        FrameViewProduct vp = new FrameViewProduct(LOACATION_ID, USER_NAME);
        vp.setVisible(true);

    }//GEN-LAST:event_jButtonViewActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed

        this.dispose();
        FrameProductEntry pe = new FrameProductEntry(LOACATION_ID, USER_NAME);
        pe.setVisible(true);

    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jTextAreaDiscriptionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextAreaDiscriptionFocusLost

        if (jTextAreaDiscription.getText().length() == 0) {
            jTextAreaDiscription.setText("NULL");
        }

    }//GEN-LAST:event_jTextAreaDiscriptionFocusLost

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered


    }//GEN-LAST:event_jPanel1MouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        FrameProductEntryUpdate peu = new FrameProductEntryUpdate(LOACATION_ID, USER_NAME);
        peu.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxSupplierFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxSupplierFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSupplierFocusGained

    private void jComboBoxSupplierFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxSupplierFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSupplierFocusLost
    public static String idSupplier;
    private void jComboBoxSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSupplierActionPerformed

        String s = jComboBoxSupplier.getSelectedItem().toString();

        idSupplier = s.substring(0, 4).toString();
        System.out.println(idSupplier);
        
        if (jComboBoxSupplier.getSelectedIndex()>0) {
            jLabelSupplier.setText("");
        }
    }//GEN-LAST:event_jComboBoxSupplierActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        FrameSupplier s= new FrameSupplier(LOACATION_ID, USER_NAME);
        s.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBoxTypeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxTypeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTypeFocusGained

    private void jComboBoxTypeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxTypeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTypeFocusLost

    private void jComboBoxTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTypeActionPerformed
        System.out.println(jComboBoxType.getSelectedIndex());
        try {
            
            if (jComboBoxType.getSelectedIndex()==1) {
                jTable1.setVisible(false);
                jScrollPane1.setVisible(false);
                jButtonRefresh.setLocation(10, 440);
                jButtonView.setLocation(90, 440);
                jButton1.setLocation(170, 440);
                jButtonSave.setLocation(700, 440);
                
                dtm.setRowCount(0);
                jTextFieldOPStock.setText("");
                
                jTextFieldIMEI1.setVisible(false);
                jTextFieldIMEI2.setVisible(false);
                jButtonAdd.setVisible(false);
                jLabel35.setVisible(false);
                jLabel36.setVisible(false);
                
                jTextFieldOPStock.setEditable(true);
                
            } else if(jComboBoxType.getSelectedIndex()==0){
                jTable1.setVisible(true);
                jScrollPane1.setVisible(true);
                jButtonRefresh.setLocation(10, 660);
                jButtonView.setLocation(90, 660);
                jButton1.setLocation(170, 660);
                jButtonSave.setLocation(700, 660);
                
                jTextFieldIMEI1.setVisible(true);
                jTextFieldIMEI2.setVisible(true);
                jButtonAdd.setVisible(true);
                jLabel35.setVisible(true);
                jLabel36.setVisible(true);
                jTextFieldOPStock.setText("");
                
                jTextFieldOPStock.setEditable(false);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jComboBoxTypeActionPerformed

    private void jTextFieldIMEI1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIMEI1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIMEI1FocusGained

    private void jTextFieldIMEI1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIMEI1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIMEI1FocusLost

    private void jTextFieldIMEI1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIMEI1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIMEI1KeyReleased

    private void jTextFieldIMEI1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIMEI1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIMEI1KeyTyped

    private void jTextFieldIMEI2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIMEI2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIMEI2FocusGained

    private void jTextFieldIMEI2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIMEI2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIMEI2FocusLost

    private void jTextFieldIMEI2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIMEI2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIMEI2KeyReleased

    private void jTextFieldIMEI2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIMEI2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIMEI2KeyTyped

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed

        if (jTextFieldProductCode.getText().length()==0 || jTextFieldIMEI1.getText().length()==0 || jTextFieldIMEI2.getText().length()==0) {
            
            if (jTextFieldProductCode.getText().length()==0) {
                jLabelProductCode.setText("Required");
            }
            
            if (jTextFieldIMEI1.getText().length()==0) {
                jLabelIMEI1.setText("Required");
            }
            
            if (jTextFieldIMEI2.getText().length()==0) {
                jLabelIMEI2.setText("Required");
            }
            
        } else {
            
            dtm =(DefaultTableModel) jTable1.getModel();
            Vector v = new Vector();
            v.add(jTextFieldProductCode.getText());
            v.add(jTextFieldIMEI1.getText());
            v.add(jTextFieldIMEI2.getText());
            v.add("REMOVE");
            dtm.addRow(v);
            jLabelOPStock.setText("");
            jTextFieldIMEI1.setText("");
            jTextFieldIMEI2.setText("");
            jTextFieldIMEI1.grabFocus();
            
            jTextFieldOPStock.setText(dtm.getRowCount()+"");
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        dtm = (DefaultTableModel) jTable1.getModel();
        
        int i = jTable1.getSelectedRow();
        int j = jTable1.getSelectedColumn();
        
        String s = jTable1.getValueAt(i, j).toString();
        
        if (s.equals("REMOVE")) {
            dtm.removeRow(i);
            jTextFieldOPStock.setText(dtm.getRowCount()+"");
        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameProductEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameProductEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameProductEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameProductEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameProductEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonView;
    public static javax.swing.JComboBox jComboBoxCategoryName;
    public static javax.swing.JComboBox jComboBoxSubCategory;
    public static javax.swing.JComboBox jComboBoxSupplier;
    public static javax.swing.JComboBox jComboBoxType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabelCategoryName;
    private javax.swing.JLabel jLabelCost;
    public static javax.swing.JLabel jLabelIMEI1;
    public static javax.swing.JLabel jLabelIMEI2;
    private javax.swing.JLabel jLabelOPStock;
    private javax.swing.JLabel jLabelProductCode;
    private javax.swing.JLabel jLabelProductName;
    private javax.swing.JLabel jLabelSellingPrice;
    private javax.swing.JLabel jLabelSubCategory;
    public static javax.swing.JLabel jLabelSupplier;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable1;
    public static javax.swing.JTextArea jTextAreaDiscription;
    public static javax.swing.JTextField jTextFieldCost;
    public static javax.swing.JTextField jTextFieldDiscount;
    public static javax.swing.JTextField jTextFieldIMEI1;
    public static javax.swing.JTextField jTextFieldIMEI2;
    public static javax.swing.JTextField jTextFieldOPStock;
    public static javax.swing.JTextField jTextFieldProductCode;
    public static javax.swing.JTextField jTextFieldProductName;
    public static javax.swing.JTextField jTextFieldSellingPrice;
    public static javax.swing.JTextField jTextFieldStockId;
    public static javax.swing.JTextField jTextFieldVat;
    // End of variables declaration//GEN-END:variables
}
