package frame;

import AppPackage.AnimationClass;
import cls.AccessPoint;
import cls.Location;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author esh
 */
public class FrameLocationMaster extends javax.swing.JFrame {

    AnimationClass AC = new AnimationClass();

    String USER_NAME = null;
    String LOCATION_ID = null;
    public static String idLocation = null;

    /**
     * Creates new form BRANCH_MASTER
     */
    public FrameLocationMaster() {
        initComponents();

    }

    public FrameLocationMaster(String LOCATIONID, String USERNAME) {
        initComponents();
        jButtonUpdate.setVisible(false);
        jCheckBoxInactive.setVisible(false);
        jLabelBranchId.setVisible(false);

        LOCATION_ID = LOCATIONID;
        USER_NAME = USERNAME;
        
        idLocation();

    }
    
    void idLocation() {

        try {

            ResultSet rs = cls.db.myConnection().createStatement().executeQuery("SELECT MAX(idlocation) FROM location");

            while (rs.next()) {

                if (rs.getInt("MAX(idlocation)") == 0) {
                    
                    jLabelBranchId.setText("1");

                } else {
                    int i = rs.getInt("MAX(idlocation)") + 1;
                    jLabelBranchId.setText(i + "");

                }
            }

        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(rootPane, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldBranchCode = new javax.swing.JTextField();
        jTextFieldBranchName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAdd = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jLabelBranchId = new javax.swing.JLabel();
        jLabelBranchCode = new javax.swing.JLabel();
        jLabelBranchName = new javax.swing.JLabel();
        jButtonSearch = new javax.swing.JButton();
        jCheckBoxInactive = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Location Master");
        setPreferredSize(new java.awt.Dimension(430, 480));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Location Master");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Location Code *");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jTextFieldBranchCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBranchCodeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBranchCodeKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldBranchCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 207, 22));

        jTextFieldBranchName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBranchNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBranchNameKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldBranchName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 207, 22));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Location Name *");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BRANCH ID", "BRANCH NAME", "BRANCH CODE", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(80);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 370, 200));

        jButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add1.png"))); // NOI18N
        jButtonAdd.setContentAreaFilled(false);
        jButtonAdd.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add2.png"))); // NOI18N
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 74, 30));

        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save1.png"))); // NOI18N
        jButtonSave.setContentAreaFilled(false);
        jButtonSave.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save2.png"))); // NOI18N
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 74, 30));

        jButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update1.png"))); // NOI18N
        jButtonUpdate.setContentAreaFilled(false);
        jButtonUpdate.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update2.png"))); // NOI18N
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 74, 30));
        jPanel1.add(jLabelBranchId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 210, 20));

        jLabelBranchCode.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelBranchCode.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelBranchCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 200, 15));

        jLabelBranchName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelBranchName.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelBranchName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 125, 200, 15));

        jButtonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search1.png"))); // NOI18N
        jButtonSearch.setContentAreaFilled(false);
        jButtonSearch.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search2.png"))); // NOI18N
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 74, 30));

        jCheckBoxInactive.setContentAreaFilled(false);
        jPanel1.add(jCheckBoxInactive, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 153, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Inactive.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 74, 26));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBranchCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBranchCodeKeyReleased

        String s = jTextFieldBranchCode.getText();
        jTextFieldBranchCode.setText(s.toUpperCase());

        jLabelBranchCode.setText("");
    }//GEN-LAST:event_jTextFieldBranchCodeKeyReleased

    private void jTextFieldBranchCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBranchCodeKeyTyped

        char c = evt.getKeyChar();

        if ((c >= '0' & c <= '9')) {
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Invalied Character");

        }
    }//GEN-LAST:event_jTextFieldBranchCodeKeyTyped

    private void jTextFieldBranchNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBranchNameKeyReleased

        String s = jTextFieldBranchName.getText();
        jTextFieldBranchName.setText(s.toUpperCase());

        jLabelBranchName.setText("");
    }//GEN-LAST:event_jTextFieldBranchNameKeyReleased

    private void jTextFieldBranchNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBranchNameKeyTyped

        char c = evt.getKeyChar();

        if ((c >= '0' & c <= '9')) {
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Invalied Character");

        }
    }//GEN-LAST:event_jTextFieldBranchNameKeyTyped

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed

        String Status = "ACTIVE";
        if (jTextFieldBranchCode.getText().length() <= 0 || jTextFieldBranchName.getText().length() <= 0) {
            if (jTextFieldBranchCode.getText().length() <= 0) {
                jLabelBranchCode.setText("Required");
            }

            if (jTextFieldBranchName.getText().length() <= 0) {
                jLabelBranchName.setText("Required");
            }

        } else {

            try {
                DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

                Vector v = new Vector();
                v.add(jLabelBranchId.getText());
                v.add(jTextFieldBranchName.getText());
                v.add(jTextFieldBranchCode.getText());
                v.add(Status);

                dtm.addRow(v);
                String id = jLabelBranchId.getText();
                int i = Integer.parseInt(id);
                i++;
                jLabelBranchId.setText(i + "");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }

        }


    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed

        DefaultTableModel dtm = null;

        if (jTable1.getRowCount() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Please add the data");

        } else {
            int s = JOptionPane.showConfirmDialog(null, "Are you sure Save.");

            if (s == JOptionPane.OK_OPTION) {
                Location l = new Location();
                l.insert();
            }

        }

    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        jButtonUpdate.setVisible(true);
        jCheckBoxInactive.setVisible(true);
        AC.jButtonXRight(280, 333, 10, 5, jButtonSearch);
        AC.jButtonXRight(270, 330, 10, 5, jButtonUpdate);
        jButtonSave.setVisible(false);
        jButtonAdd.setVisible(false);

        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);

        try {

            if (jTextFieldBranchCode.getText().length() <= 1 && jTextFieldBranchName.getText().length() <= 1) {

                Location l = new Location();
                l.refresh();

            } else if (jTextFieldBranchCode.getText().length() >= 1 || jTextFieldBranchName.getText().length() >= 1) {

                Location l = new Location();
                l.search();

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        AC.jButtonXRight(333, 333, 10, 5, jButtonSearch);
        AC.jButtonXRight(330, 330, 10, 5, jButtonUpdate);
        jButtonSave.setVisible(false);
        jButtonAdd.setVisible(false);

//        acceesPoint16();
        try {

            ResultSet rs = cls.db.myConnection().createStatement().executeQuery("SELECT * FROM location");

            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

            int i = jTable1.getSelectedRow();
            int j = jTable1.getSelectedColumn();

            String col1 = dtm.getValueAt(i, 0).toString();
            String col2 = dtm.getValueAt(i, 1).toString();
            String col3 = dtm.getValueAt(i, 2).toString();

            idLocation = col1;
            jTextFieldBranchName.setText(col2);
            jTextFieldBranchCode.setText(col3);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed

        AC.jButtonXRight(333, 333, 10, 5, jButtonSearch);
        AC.jButtonXRight(330, 330, 10, 5, jButtonUpdate);

        jButtonSave.setVisible(false);
        jButtonAdd.setVisible(false);

        if (jTextFieldBranchCode.getText().length() <= 0 || jTextFieldBranchName.getText().length() <= 0) {
            if (jTextFieldBranchCode.getText().length() <= 0) {
                jLabelBranchCode.setText("Required");
            }

            if (jTextFieldBranchName.getText().length() <= 0) {
                jLabelBranchName.setText("Required");
            }

        } else {

            AccessPoint ap = new AccessPoint();
            String status = ap.acceesPoint_02(USER_NAME);

            if (status.equals("true")) {

                int s = JOptionPane.showConfirmDialog(null, "Are you sure change.");

                if (s == JOptionPane.OK_OPTION) {

                    Location l = new Location();
                    l.update();
                }

            } else {
                jButtonUpdate.setVisible(false);
                JOptionPane.showMessageDialog(rootPane, "This access is not grant you\nCan't update details.");

            }

        }


    }//GEN-LAST:event_jButtonUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameLocationMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameLocationMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameLocationMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameLocationMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameLocationMaster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonUpdate;
    public static javax.swing.JCheckBox jCheckBoxInactive;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelBranchCode;
    private javax.swing.JLabel jLabelBranchId;
    private javax.swing.JLabel jLabelBranchName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    public static javax.swing.JTextField jTextFieldBranchCode;
    public static javax.swing.JTextField jTextFieldBranchName;
    // End of variables declaration//GEN-END:variables
}
