package frame;

import AppPackage.AnimationClass;
import cls.AccessPoint;
import cls.Employee;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.util.Scanner;
import java.util.Vector;
import javafx.animation.Animation;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author esh
 */
public class FrameCustomer extends javax.swing.JFrame {

    AnimationClass AC = new AnimationClass();
    public static String LocationID = null;
    String USER_NAME = null;
    String LOCATION_ID = null;

    /**
     * Creates new form EMPLOYEE_MASTER
     */
    public FrameCustomer() {
        initComponents();
    }

    public FrameCustomer(String LOCATIONID, String USERNAME) {
        initComponents();
        loadLocation();
        jButtonUpdate.setVisible(false);
        jCheckBoxInactive.setVisible(false);
        jLabelIDempMaster.setVisible(false);

        USER_NAME = USERNAME;
        LOCATION_ID = LOCATIONID;

        System.out.println(USER_NAME);
        System.out.println(LOCATION_ID);

    }

    void loadLocation() {

        try {

            ResultSet rs = cls.db.myConnection().createStatement().executeQuery("SELECT * FROM location");

            Vector v = new Vector();

            v.add("--SELECT--");
            while (rs.next()) {
                v.add(rs.getString("locationName"));
            }

            jComboBoxLocation.setModel(new DefaultComboBoxModel(v));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }

    }

    int month[] = {31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};

    int j;

    public int getYear() {
        j = (1900 + Integer.parseInt(jTextFieldConfirmNIC.getText().substring(0, 2)));
        return j;
    }

    public int getDays() {
        int d = Integer.parseInt(jTextFieldConfirmNIC.getText().substring(2, 5));
        if (d > 500) {
            return (d - 500);
        } else {
            return d;
        }
    }
    int mo = 0, da = 0;

    public void setMonth() {

        int days = getDays();

        for (int i = 0; i < month.length; i++) {
            if (days < month[i]) {
                mo = i + 1;
                da = days;
                break;
            } else {
                days = days - month[i];
            }
        }

    }

    public String getSex() {
        String M = "MALE", F = "FEMALE";
        int d = Integer.parseInt(jTextFieldConfirmNIC.getText().substring(2, 5));
        if (d > 500) {
            jTextFieldGender.setText(F);
            return F;
        } else {
            jTextFieldGender.setText(M);
            return M;
        }
    }

    public String search() {

        String NIC = null;
        try {

            ResultSet rs = cls.db.myConnection().createStatement().executeQuery("SELECT * FROM customer WHERE nic='" + jTextFieldConfirmNIC.getText() + "' ");

            while (rs.next()) {
                NIC = rs.getString("nic");
                String title = rs.getString("tite");
                jTextFieldNICno.setVisible(true);
                jComboBoxTitle.setSelectedItem(title);

                idCutomer = rs.getString("idcustomer");
                jTextFieldNICno.setText(rs.getString("nic"));
                jTextFieldGender.setText(rs.getString("gender"));
                jTextFieldFullName.setText(rs.getString("full_name"));
                jTextAreaIntials.setText(rs.getString("intials"));
                jTextFieldDOB.setText(rs.getString("dob"));
                jTextFieldMobile1.setText(rs.getString("mobile1"));
                jTextFieldMobile2.setText(rs.getString("mobile2"));
                jTextFieldAdd1.setText(rs.getString("address_line1"));
                jTextFieldAdd2.setText(rs.getString("address_line2"));
                jTextFieldAdd3.setText(rs.getString("address_line3"));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return NIC;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jComboBoxLocation = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldNICno = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldConfirmNIC = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jComboBoxTitle = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldFullName = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextFieldMobile1 = new javax.swing.JTextField();
        jTextFieldMobile2 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextFieldAdd1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextFieldAdd2 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextFieldAdd3 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonSave = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jCheckBoxInactive = new javax.swing.JCheckBox();
        jLabelLocation = new javax.swing.JLabel();
        jLabelNICno = new javax.swing.JLabel();
        jLabelGender = new javax.swing.JLabel();
        jLabelFullName = new javax.swing.JLabel();
        jLabelIntials = new javax.swing.JLabel();
        jLabelAdd2 = new javax.swing.JLabel();
        jLabelDateofJoin = new javax.swing.JLabel();
        jLabelsalary = new javax.swing.JLabel();
        jLabelConfirmNIC = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabeldob = new javax.swing.JLabel();
        jLabelmobile1 = new javax.swing.JLabel();
        jLabelAdd1 = new javax.swing.JLabel();
        jTextFieldGender = new javax.swing.JTextField();
        jTextFieldDOB = new javax.swing.JTextField();
        jLabelIDempMaster = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaIntials = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create New Customer");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Location *");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jComboBoxLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLocationActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 207, 22));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("NIC No *");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        jTextFieldNICno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNICnoFocusLost(evt);
            }
        });
        jTextFieldNICno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNICnoActionPerformed(evt);
            }
        });
        jTextFieldNICno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNICnoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNICnoKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldNICno, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 207, 22));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText(" Confirm NIC No *");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jTextFieldConfirmNIC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldConfirmNICFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldConfirmNICFocusLost(evt);
            }
        });
        jTextFieldConfirmNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldConfirmNICActionPerformed(evt);
            }
        });
        jTextFieldConfirmNIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldConfirmNICKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldConfirmNICKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldConfirmNICKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldConfirmNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 207, 22));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("Gender *");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("Title *");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jComboBoxTitle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--SELECT--", "MRS", "MISS", "MR", "MASTER" }));
        jComboBoxTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTitleActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 207, 22));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("Full Name *");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jTextFieldFullName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldFullNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldFullNameFocusLost(evt);
            }
        });
        jTextFieldFullName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldFullNameKeyReleased(evt);
            }
        });
        jPanel1.add(jTextFieldFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 638, 22));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText("Intials *");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setText("Mobile No 1");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jTextFieldMobile1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldMobile1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMobile1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldMobile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 207, 22));

        jTextFieldMobile2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldMobile2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMobile2KeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldMobile2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 207, 22));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setText("Mobile No 2");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setText("Addres Line 1");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jTextFieldAdd1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldAdd1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextFieldAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 207, 22));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel32.setText("Address Line 2");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, -1, -1));

        jTextFieldAdd2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldAdd2KeyReleased(evt);
            }
        });
        jPanel1.add(jTextFieldAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 207, 22));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel33.setText("Address Line 3");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jTextFieldAdd3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldAdd3KeyReleased(evt);
            }
        });
        jPanel1.add(jTextFieldAdd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 207, 22));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel36.setText("Date of Birth *");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Customer Creation");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 20));

        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save1.png"))); // NOI18N
        jButtonSave.setContentAreaFilled(false);
        jButtonSave.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save2.png"))); // NOI18N
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, 74, 30));

        jButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update1.png"))); // NOI18N
        jButtonUpdate.setContentAreaFilled(false);
        jButtonUpdate.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update2.png"))); // NOI18N
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, 74, 30));

        jCheckBoxInactive.setContentAreaFilled(false);
        jCheckBoxInactive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxInactiveActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxInactive, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 443, -1, -1));

        jLabelLocation.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLocation.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 200, 15));

        jLabelNICno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNICno.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelNICno, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 200, 15));

        jLabelGender.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelGender.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 200, 15));

        jLabelFullName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelFullName.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 225, 200, 15));

        jLabelIntials.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelIntials.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelIntials, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 275, 200, 15));

        jLabelAdd2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAdd2.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 200, 15));

        jLabelDateofJoin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDateofJoin.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelDateofJoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 525, 200, 15));

        jLabelsalary.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelsalary.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 575, 200, 15));

        jLabelConfirmNIC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelConfirmNIC.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelConfirmNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 200, 15));

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 200, 15));

        jLabeldob.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabeldob.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabeldob, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 275, 200, 15));

        jLabelmobile1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelmobile1.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelmobile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 200, 15));

        jLabelAdd1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAdd1.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 200, 15));

        jTextFieldGender.setEditable(false);
        jPanel1.add(jTextFieldGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 207, 22));

        jTextFieldDOB.setEditable(false);
        jTextFieldDOB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldDOBKeyReleased(evt);
            }
        });
        jPanel1.add(jTextFieldDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 207, 22));
        jPanel1.add(jLabelIDempMaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 200, 20));

        jTextAreaIntials.setColumns(20);
        jTextAreaIntials.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextAreaIntials.setRows(1);
        jTextAreaIntials.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextAreaIntialsKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTextAreaIntials);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 207, 22));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Inactive.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 74, 26));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed

        if (jTextFieldConfirmNIC.getText().length() <= 0 || jTextFieldFullName.getText().length() <= 0 || jTextAreaIntials.getText().length() <= 0 || jTextFieldNICno.getText().length() <= 0 || jTextFieldDOB.getText().length() <= 0 || jComboBoxLocation.getSelectedIndex() == 0
                || jComboBoxTitle.getSelectedIndex() == 0 || jTextFieldGender.getText().length() <= 1) {

            if (jTextFieldConfirmNIC.getText().length() <= 0) {
                jLabelConfirmNIC.setText("Required");
            }
            if (jTextFieldFullName.getText().length() <= 0) {
                jLabelFullName.setText("Required");
            }
            if (jTextAreaIntials.getText().length() <= 0) {
                jLabelIntials.setText("Required");
            }
            if (jTextFieldNICno.getText().length() <= 0) {
                jLabelNICno.setText("Required");
            }
            if (jTextFieldDOB.getText().length() <= 0) {
                jLabeldob.setText("Required");
            }
            if (jComboBoxLocation.getSelectedIndex() == 0) {
                jLabelLocation.setText("Required");
            }
            if (jComboBoxTitle.getSelectedIndex() == 0) {
                jLabelTitle.setText("Required");
            }
            if (jTextFieldGender.getText().length() <= 0) {
                jLabelGender.setText("Required");
            }

        } else {

            AccessPoint ap = new AccessPoint();
            String status = ap.acceesPoint_01(USER_NAME);

            if (status.equals("true")) {

                int s1 = JOptionPane.showConfirmDialog(null, "Are you sure, you want to Save?");

                if (s1 == JOptionPane.OK_OPTION) {

                    try {

                        cls.db.myConnection().createStatement().executeUpdate("INSERT INTO customer(location_idlocation, nic, tite, full_name, last_name, name_with_intials, gender, address_line1, address_line2, address_line3, mobile1, mobile2,intials,dob,status)"
                                + "VALUES('" + LocationID + "', '" + jTextFieldConfirmNIC.getText() + "', '" + jComboBoxTitle.getSelectedItem().toString() + "', '" + jTextFieldFullName.getText() + "', "
                                + "'" + lastName + "', '" + initials + "', '" + jTextFieldGender.getText() + "', '" + jTextFieldAdd1.getText() + "', '" + jTextFieldAdd2.getText() + "', "
                                + "'" + jTextFieldAdd3.getText() + "', '" + jTextFieldMobile1.getText() + "', '" + jTextFieldMobile2.getText() + "' , '" + jTextAreaIntials.getText() + "' , '" + jTextFieldDOB.getText() + "', '"+"ACTIVE"+"' )");

                        JOptionPane.showMessageDialog(null, "Sucessfully saved");

                    } catch (Exception e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(rootPane, e);
                    }

                    this.dispose();
                    FrameCustomer em = new FrameCustomer();
                    em.setVisible(true);
                }

            } else {
                jButtonUpdate.setVisible(false);
                JOptionPane.showMessageDialog(rootPane, "This access is not grant you\nCan't save details.");

            }

        }
    }//GEN-LAST:event_jButtonSaveActionPerformed
    public static String Designation = null;
    public static String Title = null;
    private void jComboBoxTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTitleActionPerformed

        Title = jComboBoxTitle.getSelectedItem().toString();
        if (jComboBoxTitle.getSelectedIndex() > 0) {
            jLabelTitle.setText("");
        }

    }//GEN-LAST:event_jComboBoxTitleActionPerformed
    public static String CivilStatus = null;
    private void jTextFieldNICnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNICnoKeyReleased

        String s = jTextFieldNICno.getText();
        jTextFieldNICno.setText(s.toUpperCase());

        jLabelNICno.setText("");

    }//GEN-LAST:event_jTextFieldNICnoKeyReleased

    private void jTextFieldConfirmNICKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldConfirmNICKeyReleased

        String s = jTextFieldConfirmNIC.getText();
        jTextFieldConfirmNIC.setText(s.toUpperCase());

        jLabelConfirmNIC.setText("");

        if (jTextFieldConfirmNIC.getText().length() == 10) {
            getSex();
            getYear();
            setMonth();
            getDays();
            jTextFieldDOB.setText(j + "" + "-" + mo + "" + "-" + da);
        }
    }//GEN-LAST:event_jTextFieldConfirmNICKeyReleased

    private void jTextFieldFullNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFullNameKeyReleased

        String s = jTextFieldFullName.getText();
        jTextFieldFullName.setText(s.toUpperCase());

        jLabelFullName.setText("");
    }//GEN-LAST:event_jTextFieldFullNameKeyReleased

    private void jTextFieldMobile1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMobile1KeyReleased

        String s = jTextFieldMobile1.getText();
        jTextFieldMobile1.setText(s.toUpperCase());

        jLabelmobile1.setText("");
    }//GEN-LAST:event_jTextFieldMobile1KeyReleased

    private void jTextFieldMobile2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMobile2KeyReleased

        String s = jTextFieldMobile2.getText();
        jTextFieldMobile2.setText(s.toUpperCase());

    }//GEN-LAST:event_jTextFieldMobile2KeyReleased

    private void jTextFieldAdd1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAdd1KeyReleased

        String s = jTextFieldAdd1.getText();
        jTextFieldAdd1.setText(s.toUpperCase());

        jLabelAdd1.setText("");
    }//GEN-LAST:event_jTextFieldAdd1KeyReleased

    private void jTextFieldAdd2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAdd2KeyReleased

        String s = jTextFieldAdd2.getText();
        jTextFieldAdd2.setText(s.toUpperCase());

        jLabelAdd2.setText("");
    }//GEN-LAST:event_jTextFieldAdd2KeyReleased

    private void jTextFieldAdd3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAdd3KeyReleased

        String s = jTextFieldAdd3.getText();
        jTextFieldAdd3.setText(s.toUpperCase());

    }//GEN-LAST:event_jTextFieldAdd3KeyReleased

    private void jComboBoxLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLocationActionPerformed

        if (jComboBoxLocation.getSelectedIndex() > 0) {
            jLabelLocation.setText("");
        }

        try {

            ResultSet rs = cls.db.myConnection().createStatement().executeQuery("SELECT * FROM location WHERE locationName='" + jComboBoxLocation.getSelectedItem().toString() + "' ");

            while (rs.next()) {
                LocationID = rs.getString("idlocation");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jComboBoxLocationActionPerformed

    private void jTextFieldNICnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNICnoFocusLost

        jTextFieldNICno.setVisible(false);
    }//GEN-LAST:event_jTextFieldNICnoFocusLost

    String LOCATION_NAME = null;
    String idCutomer = null;
    private void jTextFieldConfirmNICFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldConfirmNICFocusLost

        String s2 = jTextFieldConfirmNIC.getText();
        String s1 = jTextFieldNICno.getText();

        if (s1.equals(s2)) {
            jLabelConfirmNIC.setText("");
            jComboBoxTitle.grabFocus();
            jTextFieldNICno.setVisible(true);
        } else {
            jLabelConfirmNIC.setText("NIC No is not match");
            jTextFieldNICno.grabFocus();
        }

        String NIC = search();

        if (NIC != null) {

            if (NIC.equals(jTextFieldConfirmNIC.getText())) {
                JOptionPane.showMessageDialog(null, "NIC already used");
                jTextFieldConfirmNIC.setEditable(false);
                jLabelConfirmNIC.setText("");
                jButtonUpdate.setVisible(true);
                AC.jButtonXRight(700, 760, 10, 5, jButtonUpdate);
                jCheckBoxInactive.setVisible(true);
                jButtonSave.setVisible(false);
            }

        }


    }//GEN-LAST:event_jTextFieldConfirmNICFocusLost

    private void jTextFieldConfirmNICKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldConfirmNICKeyTyped

        char c = evt.getKeyChar();
        if (!(c >= 'v' & c <= 'x' || c >= 'V' & c <= 'X' || c >= '0' & c <= '9')) {
            evt.consume();
        }

        if (jTextFieldConfirmNIC.getText().length() > 9) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldConfirmNICKeyTyped

    private void jTextFieldConfirmNICKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldConfirmNICKeyPressed

    }//GEN-LAST:event_jTextFieldConfirmNICKeyPressed

    private void jTextFieldConfirmNICFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldConfirmNICFocusGained

    }//GEN-LAST:event_jTextFieldConfirmNICFocusGained

    private void jTextFieldNICnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNICnoKeyTyped
        char c = evt.getKeyChar();
        if (!(c >= 'v' & c <= 'x' || c >= 'V' & c <= 'X' || c >= '0' & c <= '9')) {
            evt.consume();
        }
        if (jTextFieldNICno.getText().length() > 9) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNICnoKeyTyped

    private void jTextFieldDOBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDOBKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDOBKeyReleased

    private void jTextFieldConfirmNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldConfirmNICActionPerformed

    }//GEN-LAST:event_jTextFieldConfirmNICActionPerformed
    public static String Status = null;
    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed

        if (jCheckBoxInactive.isSelected()) {
            Status = "INACTIVE";
        } else {
            Status = "ACTIVE";
        }

        if (jTextFieldAdd1.getText().length() <= 0 || jTextFieldAdd2.getText().length() <= 0 || jTextFieldConfirmNIC.getText().length() <= 0 || jTextFieldFullName.getText().length() <= 0 || jTextAreaIntials.getText().length() <= 0 || jTextFieldMobile1.getText().length() <= 0
                || jTextFieldNICno.getText().length() <= 0 || jTextFieldDOB.getText().length() <= 0 || jComboBoxLocation.getSelectedIndex() == 0 || jComboBoxTitle.getSelectedIndex() == 0 || jTextFieldGender.getText().length() <= 0) {

            if (jTextFieldAdd1.getText().length() <= 0) {
                jLabelAdd1.setText("Required");
            }
            if (jTextFieldAdd2.getText().length() <= 0) {
                jLabelAdd2.setText("Required");
            }

            if (jTextFieldConfirmNIC.getText().length() <= 0) {
                jLabelConfirmNIC.setText("Required");
            }
            if (jTextFieldFullName.getText().length() <= 0) {
                jLabelFullName.setText("Required");
            }
            if (jTextAreaIntials.getText().length() <= 0) {
                jLabelIntials.setText("Required");
            }
            if (jTextFieldMobile1.getText().length() <= 0) {
                jLabelmobile1.setText("Required");
            }
            if (jTextFieldNICno.getText().length() <= 0) {
                jLabelNICno.setText("Required");
            }
            if (jTextFieldDOB.getText().length() <= 0) {
                jLabeldob.setText("Required");
            }
            if (jComboBoxLocation.getSelectedIndex() == 0) {
                jLabelLocation.setText("Required");
            }
            if (jComboBoxTitle.getSelectedIndex() == 0) {
                jLabelTitle.setText("Required");
            }
            if (jTextFieldGender.getText().length() <= 0) {
                jLabelGender.setText("Required");
            }

        } else {

            if (jTextFieldMobile2.getText().length() == 0) {
                jTextFieldMobile2.setText("0000000000");
            }

            try {

                AccessPoint ap = new AccessPoint();
                String status = ap.acceesPoint_02(USER_NAME);

                if (status.equals("true")) {

                    int s = JOptionPane.showConfirmDialog(null, "Are you sure to update this data.");

                    if (s == JOptionPane.OK_OPTION) {

                        try {

                            ResultSet rs = cls.db.myConnection().createStatement().executeQuery("SELECT * FROM customer WHERE nic='" + jTextFieldConfirmNIC.getText() + "' ");
                            while (rs.next()) {
                                idCutomer = rs.getString("idcustomer");
                            }
                            
                            cls.db.myConnection().createStatement().executeUpdate("UPDATE customer SET location_idlocation='" + LocationID + "' ,nic='" + jTextFieldConfirmNIC.getText() + "',"
                                    + "gender='" + jTextFieldGender.getText() + "', tite='" +jComboBoxTitle.getSelectedItem().toString()+ "',full_name='" + jTextFieldFullName.getText() + "',"
                                    + "intials= '" + jTextAreaIntials.getText() + "',dob= '" + jTextFieldDOB.getText() + "', mobile1= '" + jTextFieldMobile1.getText() + "',mobile2= '" + jTextFieldMobile2.getText() + "', address_line1='" + jTextFieldAdd1.getText() + "',"
                                    + "address_line2= '" + jTextFieldAdd2.getText() + "', address_line3='" + jTextFieldAdd3.getText() + "', name_with_intials='" +initials+ "' , status='" +Status+ "'   WHERE idcustomer='" + idCutomer + "' ");

                            JOptionPane.showMessageDialog(null, "Sucessfully Update");
                            
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, e);
                            e.printStackTrace();
                        }
                        
                        this.dispose();
                        FrameCustomer em = new FrameCustomer();
                        em.setVisible(true);

                    }

                } else {
                    jButtonUpdate.setVisible(false);
                    JOptionPane.showMessageDialog(rootPane, "This access is not grant you\nCan't update details.");

                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jTextFieldNICnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNICnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNICnoActionPerformed

    private void jTextFieldMobile1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMobile1KeyTyped

        char c = evt.getKeyChar();
        if (!(c >= '0' & c <= '9')) {
            evt.consume();
        }

        if (jTextFieldMobile1.getText().length() > 9) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldMobile1KeyTyped

    private void jTextFieldMobile2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMobile2KeyTyped

        char c = evt.getKeyChar();
        if (!(c >= '0' & c <= '9')) {
            evt.consume();
        }

        if (jTextFieldMobile2.getText().length() > 9) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldMobile2KeyTyped

    private void jTextAreaIntialsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaIntialsKeyReleased

        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_TAB) {
            jTextFieldMobile1.grabFocus();
        }
    }//GEN-LAST:event_jTextAreaIntialsKeyReleased
    String lastName = null;
    String initials = null;
    private void jTextFieldFullNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFullNameFocusLost

        String s = jTextFieldFullName.getText();

        jLabelFullName.setText("");
       
            String[] arr = s.split(" ");
            // print all the initials
            for (int i = 0; i < arr.length - 1; i++) {

                jTextAreaIntials.append(arr[i].charAt(0) + ".");
            }

            // print the last name
            lastName = (arr[arr.length - 1]);

            try {

                initials = jTextAreaIntials.getText() + lastName;

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e + "\nPlease contact the system administrator");
                this.dispose();
            }

        jTextFieldMobile1.grabFocus();

    }//GEN-LAST:event_jTextFieldFullNameFocusLost

    private void jTextFieldFullNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFullNameFocusGained

        jTextAreaIntials.setText("");
    }//GEN-LAST:event_jTextFieldFullNameFocusGained

    private void jCheckBoxInactiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxInactiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxInactiveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButtonSave;
    public static javax.swing.JButton jButtonUpdate;
    public static javax.swing.JCheckBox jCheckBoxInactive;
    public static javax.swing.JComboBox jComboBoxLocation;
    public static javax.swing.JComboBox jComboBoxTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabelAdd1;
    private javax.swing.JLabel jLabelAdd2;
    public static javax.swing.JLabel jLabelConfirmNIC;
    private javax.swing.JLabel jLabelDateofJoin;
    private javax.swing.JLabel jLabelFullName;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelIDempMaster;
    private javax.swing.JLabel jLabelIntials;
    private javax.swing.JLabel jLabelLocation;
    private javax.swing.JLabel jLabelNICno;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabeldob;
    private javax.swing.JLabel jLabelmobile1;
    private javax.swing.JLabel jLabelsalary;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea jTextAreaIntials;
    public static javax.swing.JTextField jTextFieldAdd1;
    public static javax.swing.JTextField jTextFieldAdd2;
    public static javax.swing.JTextField jTextFieldAdd3;
    public static javax.swing.JTextField jTextFieldConfirmNIC;
    public static javax.swing.JTextField jTextFieldDOB;
    public static javax.swing.JTextField jTextFieldFullName;
    public static javax.swing.JTextField jTextFieldGender;
    public static javax.swing.JTextField jTextFieldMobile1;
    public static javax.swing.JTextField jTextFieldMobile2;
    public static javax.swing.JTextField jTextFieldNICno;
    // End of variables declaration//GEN-END:variables
}
