/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import cls.AccessPoint;
import cls.Stock;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author esh
 */
public class FrameStockEntry extends javax.swing.JFrame {

    String LOACATION_ID = null;
    String USER_NAME = null;

    DefaultTableModel dtm = new DefaultTableModel();    //imei table
    DefaultTableModel dtm1 = new DefaultTableModel(); // 

    public static String PRODUCT_ID = null;

    /**
     * Creates new form FrameCategory
     */
    public FrameStockEntry() {
        initComponents();
    }

    public FrameStockEntry(String LOCATIONID, String USERNAME) {
        initComponents();

        LOACATION_ID = LOCATIONID;
        USER_NAME = USERNAME;

        showTimer();

        loadSupplier();

        AutoCompleteDecorator.decorate(jComboBoxProductCode);
        AutoCompleteDecorator.decorate(jComboBoxSupplier);

        jComboBoxSupplier.grabFocus();

    }

    void showTimer() {
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                Date d = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                jTextFieldDate.setText(sdf.format(d));
            }
        }).start();
    }

    void loadSupplier() {

        try {

            ResultSet rs = cls.db.myConnection().createStatement().executeQuery("SELECT * FROM supplier WHERE status='" + "ACTIVE" + "' ");

            Vector v = new Vector();

            v.add("--SELECT--");
            while (rs.next()) {

                String idSupplier = rs.getString("idsupplier");
                String fullname = rs.getString("supplier_name");
                String setName = idSupplier + " - " + fullname;
                v.add(setName);

            }

            jComboBoxSupplier.setModel(new DefaultComboBoxModel(v));

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldStockId = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDiscription = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        jTextFieldProductName = new javax.swing.JTextField();
        jTextFieldPricePerUnit = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTextFieldQty = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextFieldTotalAmount = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonView = new javax.swing.JButton();
        jLabelDate = new javax.swing.JLabel();
        jLabelProductCode = new javax.swing.JLabel();
        jLabelProductName = new javax.swing.JLabel();
        jLabelPricePerUnit = new javax.swing.JLabel();
        jLabelSupplierName = new javax.swing.JLabel();
        jLabelQty = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBoxProductCode = new javax.swing.JComboBox();
        jLabelSupplier = new javax.swing.JLabel();
        jComboBoxSupplier = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        jTextFieldCost = new javax.swing.JTextField();
        jLabelCost = new javax.swing.JLabel();
        jTextFieldDate = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jComboBoxType = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableimei = new javax.swing.JTable();
        jLabel39 = new javax.swing.JLabel();
        jTextFieldIMEI1 = new javax.swing.JTextField();
        jLabelIMEI1 = new javax.swing.JLabel();
        jTextFieldIMEI2 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabelIMEI2 = new javax.swing.JLabel();
        jButtonAdd1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stock Entry");
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Stock Entry");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("---------------------------------------------------------------------Product Info------------------------------------------------------------------------");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 800, -1));

        jTextFieldStockId.setEditable(false);
        jTextFieldStockId.setText("01");
        jTextFieldStockId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldStockIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldStockIdFocusLost(evt);
            }
        });
        jTextFieldStockId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldStockIdKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldStockIdKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldStockId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 210, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Supplier ID*");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add1.png"))); // NOI18N
        jButtonAdd.setContentAreaFilled(false);
        jButtonAdd.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add2.png"))); // NOI18N
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 370, 74, 30));

        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save1.png"))); // NOI18N
        jButtonSave.setContentAreaFilled(false);
        jButtonSave.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save2.png"))); // NOI18N
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 650, 74, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("Product Code*");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("Product Name*");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("Price Per Unit*");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jTextAreaDiscription.setColumns(20);
        jTextAreaDiscription.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDiscription);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 210, 80));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("Date*");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        jTextFieldProductName.setEditable(false);
        jTextFieldProductName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldProductNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldProductNameFocusLost(evt);
            }
        });
        jTextFieldProductName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldProductNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldProductNameKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 210, -1));

        jTextFieldPricePerUnit.setEditable(false);
        jTextFieldPricePerUnit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPricePerUnitFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPricePerUnitFocusLost(evt);
            }
        });
        jTextFieldPricePerUnit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPricePerUnitKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPricePerUnitKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldPricePerUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 210, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel33.setText("Stock ID*");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("-----------------------------------------------------------------Stock & Supplier Details-----------------------------------------------------------------");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 800, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel35.setText("Qty*");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        jTextFieldQty.setEditable(false);
        jTextFieldQty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldQtyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldQtyFocusLost(evt);
            }
        });
        jTextFieldQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldQtyKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldQtyKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 210, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel36.setText("Total Amount");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        jTextFieldTotalAmount.setEditable(false);
        jTextFieldTotalAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldTotalAmountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTotalAmountFocusLost(evt);
            }
        });
        jTextFieldTotalAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldTotalAmountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTotalAmountKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldTotalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 210, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel37.setText("Description");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, -1));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STOCK ID", "SUPPLIER ID", "DATE", "PRODUCT CODE", "QTY", "REMARK", "DELETE", "COST"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(20);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(20);
            jTable1.getColumnModel().getColumn(7).setMinWidth(0);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(7).setMaxWidth(0);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 750, 70));

        jButtonView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/view all1.png"))); // NOI18N
        jButtonView.setContentAreaFilled(false);
        jButtonView.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/view all2.png"))); // NOI18N
        jButtonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonView, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 650, 74, 30));

        jLabelDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDate.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 200, 15));

        jLabelProductCode.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelProductCode.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelProductCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 203, 140, 15));

        jLabelProductName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelProductName.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 200, 15));

        jLabelPricePerUnit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPricePerUnit.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelPricePerUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 200, 15));

        jLabelSupplierName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSupplierName.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelSupplierName, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 200, 15));

        jLabelQty.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelQty.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 203, 200, 15));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update1.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 650, 74, 30));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh1.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh2.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 74, 30));

        jComboBoxProductCode.setEditable(true);
        jComboBoxProductCode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxProductCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProductCodeActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxProductCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 210, 21));

        jLabelSupplier.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSupplier.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 210, 15));

        jComboBoxSupplier.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBoxSupplierFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxSupplierFocusLost(evt);
            }
        });
        jComboBoxSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSupplierActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 207, 22));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText("Cost*");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jTextFieldCost.setEditable(false);
        jTextFieldCost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCostKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCostKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 210, -1));

        jLabelCost.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCost.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 200, 15));

        jTextFieldDate.setEditable(false);
        jTextFieldDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDateFocusLost(evt);
            }
        });
        jTextFieldDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldDateKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDateKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 210, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel38.setText("Type");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--SELECT--", "PHONE", "OTHER" }));
        jComboBoxType.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBoxTypeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxTypeFocusLost(evt);
            }
        });
        jComboBoxType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTypeActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxType, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 207, 22));

        jTableimei.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTableimei.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PRODUCT", "IMEI 1", "IMEI 2", "REMOVE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableimei.setRowHeight(20);
        jTableimei.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableimeiMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableimei);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 750, 120));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel39.setText("IMEI 1*");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jTextFieldIMEI1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldIMEI1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldIMEI1FocusLost(evt);
            }
        });
        jTextFieldIMEI1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldIMEI1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIMEI1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldIMEI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 210, -1));

        jLabelIMEI1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelIMEI1.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelIMEI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 210, 15));

        jTextFieldIMEI2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldIMEI2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldIMEI2FocusLost(evt);
            }
        });
        jTextFieldIMEI2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldIMEI2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIMEI2KeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldIMEI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, 210, -1));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel40.setText("IMEI 2*");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, -1, -1));

        jLabelIMEI2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelIMEI2.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabelIMEI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, 210, 15));

        jButtonAdd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add1.png"))); // NOI18N
        jButtonAdd1.setContentAreaFilled(false);
        jButtonAdd1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add2.png"))); // NOI18N
        jButtonAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdd1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 74, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldStockIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldStockIdFocusGained

    }//GEN-LAST:event_jTextFieldStockIdFocusGained

    private void jTextFieldStockIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldStockIdFocusLost

    }//GEN-LAST:event_jTextFieldStockIdFocusLost

    private void jTextFieldStockIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldStockIdKeyReleased

    }//GEN-LAST:event_jTextFieldStockIdKeyReleased

    private void jTextFieldStockIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldStockIdKeyTyped

    }//GEN-LAST:event_jTextFieldStockIdKeyTyped

    private void jTextFieldProductNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldProductNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProductNameFocusGained

    private void jTextFieldProductNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldProductNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProductNameFocusLost

    private void jTextFieldProductNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProductNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProductNameKeyReleased

    private void jTextFieldProductNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProductNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProductNameKeyTyped

    private void jTextFieldPricePerUnitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPricePerUnitFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPricePerUnitFocusGained

    private void jTextFieldPricePerUnitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPricePerUnitFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPricePerUnitFocusLost

    private void jTextFieldPricePerUnitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPricePerUnitKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPricePerUnitKeyReleased

    private void jTextFieldPricePerUnitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPricePerUnitKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPricePerUnitKeyTyped

    private void jTextFieldQtyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldQtyFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQtyFocusGained

    private void jTextFieldQtyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldQtyFocusLost

        jTextFieldIMEI1.grabFocus();
    }//GEN-LAST:event_jTextFieldQtyFocusLost

    private void jTextFieldQtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQtyKeyReleased

        Double selling_price = 0.0;
        Double qty = 0.0;
        Double totAmt = 0.0;
        String totAmtDb = null;

        if (jTextFieldQty.getText().length() > 0) {

            selling_price = Double.parseDouble(jTextFieldPricePerUnit.getText());
            qty = Double.parseDouble(jTextFieldQty.getText());
            jLabelQty.setText("");
        }

        totAmt = selling_price * qty;

        DecimalFormat df = new DecimalFormat("0.00");
        totAmtDb = df.format(totAmt);

        jTextFieldTotalAmount.setText(totAmtDb);

    }//GEN-LAST:event_jTextFieldQtyKeyReleased

    private void jTextFieldQtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQtyKeyTyped

        char c = evt.getKeyChar();
        if (!(c >= '0' & c <= '9')) {
            evt.consume();
        }

    }//GEN-LAST:event_jTextFieldQtyKeyTyped

    private void jTextFieldTotalAmountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTotalAmountFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalAmountFocusGained

    private void jTextFieldTotalAmountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTotalAmountFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalAmountFocusLost

    private void jTextFieldTotalAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTotalAmountKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalAmountKeyReleased

    private void jTextFieldTotalAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTotalAmountKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalAmountKeyTyped

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed

        if (jComboBoxProductCode.getSelectedIndex() == 0 || jTextFieldProductName.getText().length() == 0 || jTextFieldPricePerUnit.getText().length() == 0
                || jTextFieldQty.getText().length() == 0 || jTextFieldCost.getText().length() == 0 || jComboBoxSupplier.getSelectedIndex() == 0) {

            if (jComboBoxProductCode.getSelectedIndex() == 0) {
                jLabelProductCode.setText("Required");
            }

            if (jComboBoxSupplier.getSelectedIndex() == 0) {
                jLabelSupplier.setText("Required");
            }

            if (jTextFieldProductName.getText().length() == 0) {
                jLabelProductName.setText("Required");
            }

            if (jTextFieldPricePerUnit.getText().length() == 0) {
                jLabelPricePerUnit.setText("Required");
            }

            if (jTextFieldCost.getText().length() == 0) {
                jLabelCost.setText("Required");
            }

            if (jTextFieldQty.getText().length() == 0) {
                jLabelQty.setText("Required");
            }

        } else {

            dtm1 = (DefaultTableModel) jTable1.getModel();

            Vector v = new Vector();
            v.add(jTextFieldStockId.getText());
            v.add(idSupplier);
            v.add(jTextFieldDate.getText());
            v.add(PRODUCT_ID);
            v.add(jTextFieldQty.getText());
            v.add(jTextAreaDiscription.getText());
            v.add("DELETE");
            v.add(jTextFieldCost.getText());

            dtm1.addRow(v);

            jTextFieldProductName.setText("");
            jTextFieldPricePerUnit.setText("");
            jTextFieldQty.setText("");
            jTextFieldTotalAmount.setText("");
            jTextAreaDiscription.setText("");
            jTextFieldCost.setText("");

            PRODUCT_ID = null;

        }

    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed

        int i = jTable1.getRowCount();

        if (i == 0) {
            JOptionPane.showMessageDialog(rootPane, "Please add data");
        }  else {

            AccessPoint ap = new AccessPoint();
            String status = ap.acceesPoint_01(USER_NAME);

            if (status.equals("true")) {

                int s = JOptionPane.showConfirmDialog(null, "Are you sure, you want to Save?");

                if (s == JOptionPane.OK_OPTION) {

                    Stock s1 = new Stock();
                    s1.save();

                    jComboBoxProductCode.setSelectedIndex(0);
                    jTextFieldProductName.setText("");
                    jTextFieldPricePerUnit.setText("");
                    jTextFieldTotalAmount.setText("");
                    jTextAreaDiscription.setText("");

                }

            } else {

                JOptionPane.showMessageDialog(rootPane, "This access is not grant you\nCan't save details.");

            }

        }

    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewActionPerformed

        FrameViewStock vs = new FrameViewStock(LOACATION_ID, USER_NAME);
        vs.setVisible(true);

    }//GEN-LAST:event_jButtonViewActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked

    }//GEN-LAST:event_jPanel1MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered


    }//GEN-LAST:event_jPanel1MouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        FrameStockUpdate su = new FrameStockUpdate(LOACATION_ID, USER_NAME);
        su.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        DefaultTableModel dtm = new DefaultTableModel();
        dtm = (DefaultTableModel) FrameStockEntry.jTable1.getModel();

        int i = FrameStockEntry.jTable1.getSelectedRow();
        int j = FrameStockEntry.jTable1.getSelectedColumn();

        String s = dtm.getValueAt(i, j).toString();

        String s1 = "DELETE";
        System.out.println(s);
        if (s.equals(s1)) {
            dtm.removeRow(i);
        }

    }//GEN-LAST:event_jTable1MouseClicked
    String P_Code = null;
    private void jComboBoxProductCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProductCodeActionPerformed

        if (jComboBoxProductCode.getSelectedIndex() > 0 || jTextFieldProductName.getText().length() > 0 || jTextFieldPricePerUnit.getText().length() > 0
                || jTextFieldQty.getText().length() > 0 || jTextFieldCost.getText().length() > 0 || jComboBoxSupplier.getSelectedIndex() > 0) {

            if (jComboBoxProductCode.getSelectedIndex() > 0) {
                jLabelProductCode.setText("");
            }

            if (jComboBoxSupplier.getSelectedIndex() > 0) {
                jLabelSupplier.setText("");
            }

            if (jTextFieldProductName.getText().length() > 0) {
                jLabelProductName.setText("");
            }

            if (jTextFieldPricePerUnit.getText().length() > 0) {
                jLabelPricePerUnit.setText("");
            }

            if (jTextFieldCost.getText().length() > 0) {
                jLabelCost.setText("");
            }

            if (jTextFieldQty.getText().length() > 0) {
                jLabelQty.setText("");
            }

        }

        if (jComboBoxType.getSelectedIndex() == 1) {
            dtm1 = (DefaultTableModel) jTable1.getModel();
            dtm1.setRowCount(0);
            dtm = (DefaultTableModel) jTableimei.getModel();
            dtm.setRowCount(0);
        }

        jTextFieldQty.setText("");

        try {

            ResultSet rs = cls.db.myConnection().createStatement().executeQuery("SELECT * FROM product WHERE p_code='" + jComboBoxProductCode.getSelectedItem().toString() + "'");

            while (rs.next()) {

                jTextFieldProductName.setText(rs.getString("p_name"));
                jTextFieldPricePerUnit.setText(rs.getString("selling_price"));
                jTextFieldCost.setText(rs.getString("cost"));
                P_Code = rs.getString("p_code");
                PRODUCT_ID = rs.getString("idproduct");

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jComboBoxProductCodeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        this.dispose();
        FrameStockEntry se = new FrameStockEntry(LOACATION_ID, USER_NAME);
        se.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBoxSupplierFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxSupplierFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSupplierFocusGained

    private void jComboBoxSupplierFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxSupplierFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSupplierFocusLost
    public static String idSupplier;
    private void jComboBoxSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSupplierActionPerformed

        String s = jComboBoxSupplier.getSelectedItem().toString();

        idSupplier = s.substring(0, 4).toString();
        System.out.println(idSupplier);
    }//GEN-LAST:event_jComboBoxSupplierActionPerformed

    private void jTextFieldCostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCostKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCostKeyReleased

    private void jTextFieldCostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCostKeyTyped

        char c = evt.getKeyChar();
        if (!(c >= '0' & c <= '9' || c == '.')) {
            evt.consume();
        }

    }//GEN-LAST:event_jTextFieldCostKeyTyped

    private void jTextFieldDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDateFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateFocusGained

    private void jTextFieldDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDateFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateFocusLost

    private void jTextFieldDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDateKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateKeyReleased

    private void jTextFieldDateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDateKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateKeyTyped

    private void jComboBoxTypeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxTypeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTypeFocusGained

    private void jComboBoxTypeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxTypeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTypeFocusLost

    private void jComboBoxTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTypeActionPerformed

        try {

            ResultSet rs = cls.db.myConnection().createStatement().executeQuery("SELECT * FROM product WHERE type='" + jComboBoxType.getSelectedItem().toString() + "' ");

            Vector v = new Vector();
            v.add("--SELECT--");
            while (rs.next()) {

                v.add(rs.getString("p_code"));
            }

            jComboBoxProductCode.setModel(new DefaultComboBoxModel(v));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }

        try {

            if (jComboBoxType.getSelectedIndex() == 2) {
                jTableimei.setVisible(false);
                jScrollPane3.setVisible(false);

                dtm.setRowCount(0);
                dtm1.setRowCount(0);

                jTextFieldIMEI1.setVisible(false);
                jTextFieldIMEI2.setVisible(false);
                jButtonAdd1.setVisible(false);
                jLabel39.setVisible(false);
                jLabel40.setVisible(false);

                jTextFieldQty.setEditable(true);
                jTextFieldQty.setText("");

            } else if (jComboBoxType.getSelectedIndex() == 1) {
                jTableimei.setVisible(true);
                jScrollPane3.setVisible(true);

                dtm.setRowCount(0);
                dtm1.setRowCount(0);

                jTextFieldIMEI1.setVisible(true);
                jTextFieldIMEI2.setVisible(true);
                jButtonAdd1.setVisible(true);
                jLabel39.setVisible(true);
                jLabel40.setVisible(true);

                jTextFieldQty.setEditable(false);
                jTextFieldQty.setText("");

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jComboBoxTypeActionPerformed

    private void jTableimeiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableimeiMouseClicked

        dtm = (DefaultTableModel) jTableimei.getModel();

        int i = jTableimei.getSelectedRow();
        int j = jTableimei.getSelectedColumn();

        String s = jTableimei.getValueAt(i, j).toString();

        if (s.equals("REMOVE")) {
            dtm.removeRow(i);
            jTextFieldQty.setText(dtm.getRowCount() + "");
        }

    }//GEN-LAST:event_jTableimeiMouseClicked

    private void jTextFieldIMEI1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIMEI1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIMEI1FocusGained

    private void jTextFieldIMEI1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIMEI1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIMEI1FocusLost

    private void jTextFieldIMEI1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIMEI1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIMEI1KeyReleased

    private void jTextFieldIMEI1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIMEI1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIMEI1KeyTyped

    private void jTextFieldIMEI2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIMEI2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIMEI2FocusGained

    private void jTextFieldIMEI2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIMEI2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIMEI2FocusLost

    private void jTextFieldIMEI2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIMEI2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIMEI2KeyReleased

    private void jTextFieldIMEI2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIMEI2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIMEI2KeyTyped

    private void jButtonAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdd1ActionPerformed

        if (jComboBoxProductCode.getSelectedIndex() == 0 || jTextFieldIMEI1.getText().length() == 0 || jTextFieldIMEI2.getText().length() == 0) {

            if (jComboBoxProductCode.getSelectedIndex() == 0) {
                jLabelProductCode.setText("Required");
            }

            if (jTextFieldIMEI1.getText().length() == 0) {
                jLabelIMEI1.setText("Required");
            }

            if (jTextFieldIMEI2.getText().length() == 0) {
                jLabelIMEI2.setText("Required");
            }

        } else {

            dtm = (DefaultTableModel) jTableimei.getModel();
            Vector v = new Vector();
            v.add(PRODUCT_ID);
            v.add(jTextFieldIMEI1.getText());
            v.add(jTextFieldIMEI2.getText());
            v.add("REMOVE");
            dtm.addRow(v);
            jLabelQty.setText("");
            jTextFieldIMEI1.setText("");
            jTextFieldIMEI2.setText("");
            jTextFieldIMEI1.grabFocus();

            jTextFieldQty.setText(dtm.getRowCount() + "");
        }
    }//GEN-LAST:event_jButtonAdd1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameStockEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameStockEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameStockEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameStockEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameStockEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAdd1;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonView;
    public static javax.swing.JComboBox jComboBoxProductCode;
    public static javax.swing.JComboBox jComboBoxSupplier;
    public static javax.swing.JComboBox jComboBoxType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    public static javax.swing.JLabel jLabelCost;
    private javax.swing.JLabel jLabelDate;
    public static javax.swing.JLabel jLabelIMEI1;
    public static javax.swing.JLabel jLabelIMEI2;
    public static javax.swing.JLabel jLabelPricePerUnit;
    public static javax.swing.JLabel jLabelProductCode;
    public static javax.swing.JLabel jLabelProductName;
    private javax.swing.JLabel jLabelQty;
    public static javax.swing.JLabel jLabelSupplier;
    public static javax.swing.JLabel jLabelSupplierName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTable jTable1;
    public static javax.swing.JTable jTableimei;
    private javax.swing.JTextArea jTextAreaDiscription;
    public static javax.swing.JTextField jTextFieldCost;
    public static javax.swing.JTextField jTextFieldDate;
    public static javax.swing.JTextField jTextFieldIMEI1;
    public static javax.swing.JTextField jTextFieldIMEI2;
    public static javax.swing.JTextField jTextFieldPricePerUnit;
    public static javax.swing.JTextField jTextFieldProductName;
    public static javax.swing.JTextField jTextFieldQty;
    public static javax.swing.JTextField jTextFieldStockId;
    public static javax.swing.JTextField jTextFieldTotalAmount;
    // End of variables declaration//GEN-END:variables
}
